import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import PageTemplate from "../components/PageTemplate";
import RelatedAnalyses from "../components/RelatedAnalyses";
import FeedbackWidget from "../components/FeedbackWidget";
import { trackPageView } from "../analytics";
import { HOST } from "../apis/ShortPositionAPI";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine,
} from "recharts";

const SLUG = "ambu/2026-06-01";

// ─── types ───────────────────────────────────────────────────────────────────
interface ComparisonPoint {
  date: string;
  ambu: number;
  olympus: number;
  bsx: number;
  colo: number;
  isrg: number;
}

interface MarginPoint {
  fy: string;
  margin: number;
}

interface ShortHolder {
  name: string;
  value: number;
  date: string;
}

// ─── static data ────────────────────────────────────────────────────────────
// Generated by yfinance daily close, last trading day of month, normalised to 100.
// Window: 2020-01 → 2026-05 (Jan 2020 = 100, pre-pandemic baseline).
const COMPARISON_DATA: ComparisonPoint[] = [
  { date: "2020-01", ambu: 100.0, olympus: 100.0, bsx: 100.0, colo: 100.0, isrg: 100.0 },
  { date: "2020-02", ambu: 124.0, olympus: 109.9, bsx: 89.3, colo: 106.3, isrg: 95.4 },
  { date: "2020-03", ambu: 133.8, olympus: 87.5, bsx: 77.9, colo: 115.9, isrg: 88.5 },
  { date: "2020-04", ambu: 173.0, olympus: 96.7, bsx: 89.5, colo: 126.6, isrg: 91.3 },
  { date: "2020-05", ambu: 181.3, olympus: 104.9, bsx: 90.7, colo: 132.2, isrg: 103.6 },
  { date: "2020-06", ambu: 168.7, olympus: 116.3, bsx: 83.9, colo: 120.8, isrg: 101.8 },
  { date: "2020-07", ambu: 178.1, olympus: 105.5, bsx: 92.1, colo: 126.4, isrg: 122.4 },
  { date: "2020-08", ambu: 148.5, olympus: 117.6, bsx: 98.0, colo: 124.4, isrg: 130.6 },
  { date: "2020-09", ambu: 145.7, olympus: 122.3, bsx: 91.3, colo: 117.9, isrg: 126.8 },
  { date: "2020-10", ambu: 156.9, olympus: 111.5, bsx: 81.8, colo: 109.6, isrg: 119.2 },
  { date: "2020-11", ambu: 169.3, olympus: 126.4, bsx: 79.2, colo: 109.5, isrg: 129.7 },
  { date: "2020-12", ambu: 213.1, olympus: 126.4, bsx: 85.9, colo: 109.2, isrg: 146.1 },
  { date: "2021-01", ambu: 235.2, olympus: 105.9, bsx: 84.6, colo: 107.8, isrg: 133.6 },
  { date: "2021-02", ambu: 231.1, olympus: 125.0, bsx: 92.6, colo: 110.3, isrg: 131.6 },
  { date: "2021-03", ambu: 241.2, olympus: 128.4, bsx: 92.3, colo: 112.1, isrg: 132.0 },
  { date: "2021-04", ambu: 280.6, olympus: 125.9, bsx: 104.1, colo: 120.3, isrg: 154.5 },
  { date: "2021-05", ambu: 183.8, olympus: 131.7, bsx: 101.6, colo: 112.9, isrg: 150.4 },
  { date: "2021-06", ambu: 195.2, olympus: 123.7, bsx: 102.1, colo: 120.9, isrg: 164.3 },
  { date: "2021-07", ambu: 187.9, olympus: 125.8, bsx: 108.9, colo: 134.8, isrg: 177.1 },
  { date: "2021-08", ambu: 161.2, olympus: 129.5, bsx: 107.8, colo: 128.2, isrg: 188.2 },
  { date: "2021-09", ambu: 153.7, olympus: 137.7, bsx: 103.6, colo: 118.3, isrg: 177.6 },
  { date: "2021-10", ambu: 148.4, olympus: 137.9, bsx: 103.0, colo: 123.3, isrg: 193.5 },
  { date: "2021-11", ambu: 150.4, olympus: 142.3, bsx: 90.9, colo: 126.1, isrg: 173.8 },
  { date: "2021-12", ambu: 140.1, olympus: 148.5, bsx: 101.5, colo: 135.3, isrg: 192.6 },
  { date: "2022-01", ambu: 112.8, olympus: 142.7, bsx: 102.5, colo: 112.6, isrg: 152.3 },
  { date: "2022-02", ambu: 99.4, olympus: 128.9, bsx: 105.5, colo: 117.3, isrg: 155.6 },
  { date: "2022-03", ambu: 81.0, olympus: 131.1, bsx: 105.8, colo: 120.4, isrg: 161.7 },
  { date: "2022-04", ambu: 76.5, olympus: 129.4, bsx: 100.6, colo: 112.7, isrg: 128.2 },
  { date: "2022-05", ambu: 76.9, olympus: 150.8, bsx: 97.9, colo: 96.9, isrg: 122.0 },
  { date: "2022-06", ambu: 55.8, olympus: 152.8, bsx: 89.0, colo: 95.0, isrg: 107.6 },
  { date: "2022-07", ambu: 66.8, olympus: 157.9, bsx: 98.0, colo: 99.8, isrg: 123.4 },
  { date: "2022-08", ambu: 60.4, olympus: 168.7, bsx: 96.3, colo: 99.7, isrg: 110.3 },
  { date: "2022-09", ambu: 53.8, olympus: 155.7, bsx: 92.5, colo: 91.2, isrg: 100.5 },
  { date: "2022-10", ambu: 68.3, olympus: 176.0, bsx: 103.0, colo: 98.7, isrg: 132.1 },
  { date: "2022-11", ambu: 71.8, olympus: 157.2, bsx: 108.1, colo: 98.0, isrg: 144.9 },
  { date: "2022-12", ambu: 72.1, olympus: 131.8, bsx: 110.5, colo: 95.4, isrg: 142.2 },
  { date: "2023-01", ambu: 76.1, olympus: 136.1, bsx: 110.5, colo: 96.7, isrg: 131.7 },
  { date: "2023-02", ambu: 83.7, olympus: 128.6, bsx: 111.6, colo: 95.6, isrg: 122.9 },
  { date: "2023-03", ambu: 83.2, olympus: 129.9, bsx: 119.5, colo: 106.0, isrg: 136.9 },
  { date: "2023-04", ambu: 86.8, olympus: 132.7, bsx: 124.5, colo: 114.3, isrg: 161.4 },
  { date: "2023-05", ambu: 88.3, olympus: 118.7, bsx: 123.0, colo: 103.1, isrg: 165.0 },
  { date: "2023-06", ambu: 90.4, olympus: 127.0, bsx: 129.2, colo: 100.3, isrg: 183.3 },
  { date: "2023-07", ambu: 81.0, olympus: 129.8, bsx: 123.8, colo: 99.0, isrg: 173.9 },
  { date: "2023-08", ambu: 67.6, olympus: 110.4, bsx: 128.8, colo: 92.3, isrg: 167.6 },
  { date: "2023-09", ambu: 59.8, olympus: 108.8, bsx: 126.1, colo: 87.8, isrg: 156.6 },
  { date: "2023-10", ambu: 56.3, olympus: 112.0, bsx: 122.3, colo: 86.4, isrg: 140.5 },
  { date: "2023-11", ambu: 75.4, olympus: 121.4, bsx: 133.5, colo: 94.9, isrg: 166.6 },
  { date: "2023-12", ambu: 85.2, olympus: 114.3, bsx: 138.1, colo: 90.7, isrg: 180.8 },
  { date: "2024-01", ambu: 93.0, olympus: 123.3, bsx: 151.1, colo: 93.7, isrg: 202.7 },
  { date: "2024-02", ambu: 97.7, olympus: 119.5, bsx: 158.1, colo: 107.6, isrg: 206.7 },
  { date: "2024-03", ambu: 91.9, olympus: 124.2, bsx: 163.6, colo: 109.6, isrg: 213.9 },
  { date: "2024-04", ambu: 91.1, olympus: 123.3, bsx: 171.7, colo: 99.5, isrg: 198.6 },
  { date: "2024-05", ambu: 106.4, olympus: 138.6, bsx: 180.5, colo: 96.9, isrg: 215.5 },
  { date: "2024-06", ambu: 108.5, olympus: 145.3, bsx: 183.9, colo: 98.3, isrg: 238.4 },
  { date: "2024-07", ambu: 113.3, olympus: 145.9, bsx: 176.5, colo: 105.4, isrg: 238.3 },
  { date: "2024-08", ambu: 103.6, olympus: 149.0, bsx: 195.3, colo: 108.1, isrg: 264.0 },
  { date: "2024-09", ambu: 106.2, olympus: 152.3, bsx: 200.1, colo: 102.8, isrg: 263.3 },
  { date: "2024-10", ambu: 102.8, olympus: 151.9, bsx: 200.7, colo: 100.5, isrg: 270.0 },
  { date: "2024-11", ambu: 89.9, olympus: 132.2, bsx: 216.5, colo: 104.5, isrg: 290.5 },
  { date: "2024-12", ambu: 84.2, olympus: 132.8, bsx: 213.3, colo: 92.4, isrg: 279.7 },
  { date: "2025-01", ambu: 109.1, olympus: 132.6, bsx: 244.5, colo: 97.5, isrg: 306.5 },
  { date: "2025-02", ambu: 106.5, olympus: 114.7, bsx: 247.9, colo: 89.8, isrg: 307.2 },
  { date: "2025-03", ambu: 95.5, olympus: 109.1, bsx: 240.9, colo: 85.0, isrg: 265.4 },
  { date: "2025-04", ambu: 95.3, olympus: 104.5, bsx: 245.7, colo: 87.2, isrg: 276.4 },
  { date: "2025-05", ambu: 82.0, olympus: 104.0, bsx: 251.4, colo: 74.7, isrg: 296.0 },
  { date: "2025-06", ambu: 80.5, olympus: 96.1, bsx: 256.5, colo: 70.7, isrg: 291.2 },
  { date: "2025-07", ambu: 78.0, olympus: 101.5, bsx: 250.6, colo: 70.9, isrg: 257.8 },
  { date: "2025-08", ambu: 77.9, olympus: 96.5, bsx: 252.0, colo: 72.0, isrg: 253.7 },
  { date: "2025-09", ambu: 75.0, olympus: 104.8, bsx: 233.2, colo: 63.8, isrg: 239.7 },
  { date: "2025-10", ambu: 81.5, olympus: 106.4, bsx: 240.6, colo: 68.8, isrg: 286.3 },
  { date: "2025-11", ambu: 70.7, olympus: 117.7, bsx: 242.6, colo: 68.2, isrg: 307.3 },
  { date: "2025-12", ambu: 71.3, olympus: 111.2, bsx: 227.7, colo: 64.2, isrg: 303.5 },
  { date: "2026-01", ambu: 68.9, olympus: 103.2, bsx: 223.4, colo: 63.0, isrg: 270.2 },
  { date: "2026-02", ambu: 64.4, olympus: 85.6, bsx: 183.5, colo: 57.3, isrg: 269.8 },
  { date: "2026-03", ambu: 55.4, olympus: 83.4, bsx: 149.9, colo: 51.3, isrg: 247.1 },
  { date: "2026-04", ambu: 51.1, olympus: 86.7, bsx: 137.6, colo: 46.3, isrg: 245.2 },
  { date: "2026-05", ambu: 54.6, olympus: 100.1, bsx: 115.4, colo: 46.5, isrg: 227.6 },
];

// Operating margin per fiscal year (Ambu's fiscal years end in September)
// FY20/21 to FY23/24 from yfinance Total Revenue / Operating Income.
// FY24/25 from Ambu Interim Report Q4 2024/25 (November 5, 2025): EBIT before special items 13.0%.
const MARGIN_DATA: MarginPoint[] = [
  { fy: "FY20/21", margin: 8.5 },
  { fy: "FY21/22", margin: 2.7 },
  { fy: "FY22/23", margin: 6.3 },
  { fy: "FY23/24", margin: 12.0 },
  { fy: "FY24/25", margin: 13.0 },
];

// Current large short positions in Ambu (Zirium's own database, May 29, 2026)
const SHORT_HOLDERS: ShortHolder[] = [
  { name: "Wellington Management International Limited", value: 0.82, date: "May 14, 2026" },
  { name: "Millennium International Management LP",      value: 0.80, date: "May 27, 2026" },
  { name: "AHL Partners LLP",                            value: 0.70, date: "May 4, 2026" },
  { name: "J.P. Morgan Asset Management (UK) Limited",   value: 0.68, date: "Nov 6, 2025" },
  { name: "BlackRock Financial Management, Inc.",        value: 0.50, date: "May 1, 2026" },
  { name: "BlackRock Advisors, LLC",                     value: 0.50, date: "Apr 23, 2026" },
];

// ─── helpers ─────────────────────────────────────────────────────────────────
const formatDate = (ym: string): string => {
  const [y, m] = ym.split("-");
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return `${months[parseInt(m, 10) - 1]} ${y.slice(2)}`;
};

// ─── sub-components ──────────────────────────────────────────────────────────
function KPI({ value, label, highlight, tone = "blue" }: { value: string; label: string; highlight?: boolean; tone?: "blue" | "red" | "green" }) {
  const toneClasses = {
    blue:  { bg: "bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800",       text: "text-blue-600 dark:text-blue-400" },
    red:   { bg: "bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800",           text: "text-red-700 dark:text-red-400" },
    green: { bg: "bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800", text: "text-emerald-700 dark:text-emerald-400" },
  };
  const t = toneClasses[tone];
  return (
    <div className={`rounded-2xl border p-4 sm:p-5 text-center ${highlight ? t.bg : "bg-white dark:bg-[#19191f] border-gray-100 dark:border-gray-800"}`}>
      <p className={`text-lg sm:text-xl font-bold tabular-nums ${highlight ? t.text : "text-gray-900 dark:text-white"}`}>{value}</p>
      <p className="text-xs text-gray-500 dark:text-gray-300 mt-1 leading-tight">{label}</p>
    </div>
  );
}

function SectionHeader({ n, title }: { n: number; title: string }) {
  return (
    <h2 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-4">
      {n}. {title}
    </h2>
  );
}

function TimelineEvent({ date, title, children, color }: { date: string; title: string; children: React.ReactNode; color: string }) {
  return (
    <div className="relative pl-8 pb-8 last:pb-0 group">
      <div className="absolute left-0 top-1 w-4 h-4 rounded-full border-2 border-white dark:border-[#0d0d12] z-10" style={{ backgroundColor: color }} />
      <div className="absolute left-[7px] top-5 bottom-0 w-0.5 bg-gray-200 dark:bg-gray-700 group-last:hidden" />
      <p className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-1">{date}</p>
      <h4 className="font-semibold text-gray-900 dark:text-white mb-1.5">{title}</h4>
      <div className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed">{children}</div>
    </div>
  );
}

// ─── main page ───────────────────────────────────────────────────────────────
const AmbuAnalysisPageEn: React.FC = () => {
  const navigate = useNavigate();

  useEffect(() => {
    trackPageView(`/analyse/${SLUG}`, "Ambu analysis");
    fetch(`${HOST}/stats/visit/ambu-analysis/`).catch(() => {});
  }, []);

  return (
    <PageTemplate>
      <title>Ambu: Falling despite a successful transformation | Zirium</title>
      <meta
        name="description"
        content="Ambu sits 45% below its pre-pandemic level, even though the company has operationally carried out a strong transformation under CEO Britt Meelby Jensen with a nearly quintupled margin. Yet the stock keeps falling. We examine the paradox, the tariff pressure and the hedge funds' high short interest."
      />
      <meta property="og:title" content="Ambu: Falling despite a successful transformation" />
      <meta property="og:description" content="Ambu sits 45% below its pre-pandemic level despite a nearly quintupled margin. Hedge funds hold high short interest. What is the paradox?" />
      <meta property="og:type" content="article" />
      <meta property="og:url" content={`https://www.zirium.dk/analyse/${SLUG}`} />
      <meta property="og:image" content="https://www.zirium.dk/og-images/ambu-2026-06-01-en.png" />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:type" content="image/png" />
      <meta property="og:site_name" content="Zirium" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Ambu: Falling despite a successful transformation" />
      <meta name="twitter:description" content="Ambu sits 45% below its pre-pandemic level despite a nearly quintupled margin. Hedge funds hold high short interest." />
      <meta name="twitter:image" content="https://www.zirium.dk/og-images/ambu-2026-06-01-en.png" />
      <script type="application/ld+json">{JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "Ambu: Falling despite a successful transformation",
        "description": "Ambu sits 45% below its pre-pandemic level from 2020. Operationally the company has carried out a strong transformation, but the stock keeps falling.",
        "author": { "@type": "Person", "name": "Araz Bayat Makoo" },
        "publisher": { "@type": "Organization", "name": "Zirium", "url": "https://www.zirium.dk" },
        "datePublished": "2026-06-01",
        "mainEntityOfPage": `https://www.zirium.dk/analyse/${SLUG}`,
        "inLanguage": "en",
      })}</script>

      <article className="w-full max-w-[900px] mx-auto px-5 sm:px-8 pb-10 sm:pb-16">
        <button
          className="text-blue-600 hover:text-blue-700 bg-transparent border-none text-base inline-flex items-center gap-1.5 focus:ring-2 focus:ring-blue-300 rounded-sm min-h-[44px] min-w-[44px]"
          onClick={() => {
            if (window.history.length > 1 && window.history.state?.idx > 0) {
              navigate(-1);
            } else {
              navigate("/analyse");
            }
          }}
        >
          <span aria-hidden="true">←</span>
          Back
        </button>

        {/* Header */}
        <header className="mb-10 mt-4">
          <p className="text-base text-gray-600 dark:text-gray-300 mb-4">
            Analysis by Araz Bayat Makoo (Zirium) - June 1, 2026
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-gray-900 dark:text-white mb-3 leading-tight">
            Ambu: Falling despite a successful transformation
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 leading-relaxed">
            Ambu A/S (AMBU-B)
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Ambu is one of the most paradoxical stories on the Danish stock
            exchange right now. Operationally, the company has carried out one
            of the strongest transformations in the Danish healthcare sector
            under CEO Britt Meelby Jensen: The operating margin before special
            items has nearly quintupled from 2.7% in fiscal year 2021/22 to
            13.0% in 2024/25, organic revenue growth came in at 13.1% in the
            most recent fiscal year, and the company now holds more cash than
            debt. Yet the stock keeps falling. Why?
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            The share price today sits around DKK 67.40, roughly 45% below its
            pre-pandemic level and roughly 81% below the pandemic peak from
            April 2021. A large part of the decline is not due to weak
            operations, but to a correction of an extreme valuation: At its
            peak, the stock traded at a P/E well above 100 on trailing
            earnings. Such high multiples have historically rarely been
            sustainable without extreme and persistent growth, and when both
            growth and margins normalised at the same time, a sharp pullback
            followed.
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            We review the share price development since 2020 compared with its
            competitors, the transformation under the ZOOM IN strategy, the new
            ZOOM AHEAD plan toward FY29/30, the current tariff pressure and the
            hedge funds' high short interest in the company.
          </p>
        </header>

        {/* KPIs */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-12">
          <KPI value="-45%" label="Return since Jan 2020" highlight tone="red" />
          <KPI value="+188%" label="To the pandemic peak (Apr 2021)" />
          <KPI value="-81%" label="From record high" />
          <KPI value="6.96%" label="Short interest (May 29)" highlight tone="red" />
        </div>

        {/* Section 1 */}
        <section className="mb-12">
          <SectionHeader n={1} title="How big is the problem really?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            The comparison since January 2020, that is, before the pandemic,
            tells two things. First, this is not a broad sector crisis:
            Intuitive Surgical has more than doubled (+128%), Boston Scientific
            is up 15%, and even Japanese Olympus (the clear reusable-instrument
            competitor) is roughly back at its starting level (around 0%).
            Second, Ambu's share price journey is unique: The stock nearly
            tripled to the pandemic peak and has now fallen all the way back to
            roughly 45% below its starting point. Only Coloplast (-53%) has a
            similar overall decline, but without Ambu's extreme spike up and
            down.
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Chart: Comparison of Ambu vs Olympus, Boston Scientific, Coloplast and Intuitive Surgical since January 2020">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Ambu vs. 4 medical device peers (Jan 2020 = 100)</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Month-end, price index (excluding dividends), local currency</p>
            <ResponsiveContainer width="100%" height={320}>
              <LineChart data={COMPARISON_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis
                  dataKey="date"
                  tick={{ fontSize: 11, fill: "#6b7280" }}
                  tickFormatter={formatDate}
                  interval={11}
                />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} domain={[40, 320]} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => Number(v).toFixed(1)}
                  labelFormatter={(label) => formatDate(String(label))}
                />
                <Legend wrapperStyle={{ fontSize: 12 }} />
                <ReferenceLine y={100} stroke="#9ca3af" strokeDasharray="3 3" />
                <Line type="monotone" dataKey="isrg" name="Intuitive Surgical" stroke="#10b981" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="bsx" name="Boston Scientific" stroke="#3b82f6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="olympus" name="Olympus" stroke="#f59e0b" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="colo" name="Coloplast" stroke="#8b5cf6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="ambu" name="Ambu" stroke="#ef4444" strokeWidth={3} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>

          <p className="text-xs text-gray-500 dark:text-gray-400 italic leading-relaxed">
            Note: The chart shows price development only and does not include
            dividends, so the total return for dividend-paying companies is in
            reality higher than shown. The index is normalised to 100 in
            January 2020. Returns are measured in local currency and are not
            currency-adjusted. For Olympus (listed in JPY), adjusting to DKK
            would pull the level shown (around 0%) down into negative
            territory, since the yen has weakened markedly against the krone
            over the period.
          </p>
        </section>

        {/* Section 2 */}
        <section className="mb-12">
          <SectionHeader n={2} title="Pandemic euphoria, bubble valuation and collapse" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Ambu's peak price of DKK 355.40 on April 27, 2021 was the result
            of a perfect storm during COVID-19. Single-use endoscopes, which
            were Ambu's core product, were suddenly seen as an
            infection-control solution, because reusable instruments required
            reprocessing that was regarded as a risk factor during the
            pandemic. Hospitals bought heavily and built up inventories far
            above the normal consumption rate.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            The combined effect was dramatic on both earnings and valuation.
            The stock nearly tripled from January 2020 to April 2021, and the
            market priced Ambu as if single-use endoscopy were about to take
            over the entire endoscopy market within a few years. At its peak,
            the stock traded at a P/E well above 100 on trailing earnings, a
            level historically seen only in pure narrative stocks at extreme
            bubble tops.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            This means that a large part of Ambu's subsequent decline was a
            valuation reset rather than pure operational criticism. Even if
            earnings had stayed constant, a drop in the multiple from above
            100x to around 25x would by itself have cut the stock to a quarter.
            But the decline was not only about the multiple: 2021-2022 was
            above all a valuation reset, while 2022-2024 was also marked by
            genuine fundamental disappointment. Earnings collapsed (EBIT margin
            from 8.5% in 2020/21 to 2.7% in 2021/22), growth slowed as
            hospitals' pandemic inventories normalised, and single-use adoption
            in the gastrointestinal (GI) segment progressed more slowly than
            hoped.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            The internal corporate governance history also includes the Lars
            Marcher case from May 10, 2019, where the dismissed CEO held 3.8
            million shares privately and would not comment on whether he sold
            after his dismissal, once the disclosure requirement no longer
            applied. The Danish Shareholders' Association criticised this as a
            loophole. The episode is not a direct cause of the decline since
            2021, but it shaped a period in which many institutional investors
            became cautious about Ambu as a management case. It was Juan José
            González who took over as CEO after Marcher and led Ambu through
            the entire boom-and-bust period, until in May 2022 the board
            brought in Britt Meelby Jensen to lead the recovery.
          </p>
        </section>

        {/* Section 3 */}
        <section className="mb-12">
          <SectionHeader n={3} title="ZOOM IN: Britt Meelby Jensen's turnaround" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Britt Meelby Jensen took office as CEO on May 20, 2022. She arrived
            with a rare combination of backgrounds: CEO of Atos Medical
            (medical device) until she sold the company to Coloplast in early
            2022, and before that CEO of Zealand Pharma from 2015 to 2019. She
            understands both medical device commercial expansion and pharma
            pipeline execution.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            In November 2022 she launched the ZOOM IN strategy, a three-year
            recovery plan focused on restoring earnings and paying down debt.
            The strategy was executed over the following three years through
            2025. The chart shows the margin progression clearly:
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Chart: Ambu's operating margin progression FY21 to FY24">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Ambu operating margin per fiscal year</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Margin (%) per fiscal year (ending September 30). Source: Ambu annual reports.</p>
            <ResponsiveContainer width="100%" height={260}>
              <BarChart data={MARGIN_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis dataKey="fy" tick={{ fontSize: 11, fill: "#6b7280" }} />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} tickFormatter={(v) => `${v}%`} domain={[0, 18]} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => `${Number(v).toFixed(1)}%`}
                />
                <Bar dataKey="margin" name="EBIT margin" fill="#2563eb" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            The margin has nearly quintupled from 2.7% to 13.0% over three
            fiscal years. In FY24/25 (ended September 30, 2025), Ambu delivered
            organic revenue growth of 13.1%, free cash flow before acquisitions
            of DKK 407 million, and the company ended with a net cash position
            of DKK 319 million. At the same time, the board has resolved to
            return DKK 260 million to shareholders via dividends (DKK 110
            million) and share buybacks (DKK 150 million). Operationally, the
            transformation is real and confirmed in the official figures.
          </p>
        </section>

        {/* Section 4 */}
        <section className="mb-12">
          <SectionHeader n={4} title="ZOOM AHEAD: new ambitions toward FY29/30" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            In September 2025, Ambu announced the follow-up strategy ZOOM
            AHEAD, which raises the long-term targets. For FY29/30, Ambu now
            has the following official targets:
          </p>
          <ul className="space-y-2 text-gray-600 dark:text-gray-300 leading-relaxed list-disc pl-6 mb-4">
            <li><strong>Organic revenue growth of 11-13% CAGR</strong> (up from +10% toward FY27/28)</li>
            <li><strong>Endoscopy Solutions: 15-20% CAGR</strong> as the growth engine</li>
            <li><strong>Anaesthesia &amp; Patient Monitoring: 3-5% CAGR</strong> as a stable base</li>
            <li><strong>EBIT margin of +20%</strong> (same level as the previous FY27/28 target)</li>
            <li><strong>Cash conversion of +40%</strong> (FCF before acquisitions / EBITDA)</li>
          </ul>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Endoscopy Solutions is the centrepiece and contains the core
            product line aScope. Most recently, Ambu has launched aScope 5
            Broncho (a top-tier bronchoscope), aScope Gastro Large (a 4.2 mm
            working channel for advanced GI procedures) and is developing a
            colonoscopy line. The strategy is about extending the single-use
            model to markets where Olympus' reusable instruments still
            dominate.
          </p>
        </section>

        {/* Section 5 */}
        <section className="mb-12">
          <SectionHeader n={5} title="Tariff pressure and a weaker Q2" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            On November 5, 2025, Ambu reported its FY24/25 results, and the
            stock fell roughly 16% on the day. The reason was not weak
            operations, but a combination of tariff costs and currency
            headwinds. Q4 FY24/25 (the quarter July to September 2025)
            delivered an EBIT margin before special items of 10.0% versus
            consensus of around 12-13%. The tariff effect and a weakened USD
            against DKK were mainly responsible.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            The Trump administration's tariffs on medical products
            manufactured outside the U.S. hit Ambu particularly hard, because
            Ambu's primary production centres are located in Malaysia and
            Mexico. The company has announced a plan to move all of its North
            American endoscopy demand to local production by FY29/30, but until
            then Ambu has to absorb the costs.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            With the annual results, Ambu guided FY25/26 to organic revenue
            growth of 10-13% and an EBIT margin before special items of 12-14%
            (14-16% excluding the tariff impact of roughly 2 percentage
            points). This is the primary reason that margins fall briefly after
            peaking at 16.1% in Q1 FY24/25 (the quarter October to December
            2024).
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            On May 6, 2026, the Q2 results for 2025/26 confirmed the market's
            concern. Organic growth slowed to 7.3% in the quarter versus 13.1%
            for the full FY24/25. Endoscopy Solutions continued to grow
            strongly (+13.8%), but Anaesthesia &amp; Patient Monitoring fell
            2.5%, and the EBIT margin came in at 11.0% in the quarter. At the
            same time, Ambu lowered its full-year guidance for organic growth
            to 10-12% (from 10-13%). For a market that already doubted
            execution, a growth slowdown combined with a downgrade was exactly
            the wrong signal.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            As a countermeasure, the board simultaneously launched a share
            buyback of up to DKK 300 million, running from May 6 to no later
            than September 30, 2026. It signals that management itself regards
            the stock as undervalued, and may provide some support under the
            share price in the short term.
          </p>
        </section>

        {/* Section 6 */}
        <section className="mb-12">
          <SectionHeader n={6} title="The hedge funds' high short interest" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            On May 29, 2026, total short interest in Ambu stood at 6.96% of the
            share capital. The peak of 7.38% was reached on May 7, 2026, only
            three weeks before this analysis. It is the highest level we have
            recorded for Ambu over the period, and it indicates considerable
            scepticism among parts of the professional investor base toward the
            ZOOM AHEAD targets. High short interest can, however, also reflect
            factor, pair or market-neutral strategies and not purely
            fundamental scepticism.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            The largest publicly disclosed short positions come from a mix of
            multi-strategy hedge funds and large asset managers:
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-4 sm:p-5 mb-4 overflow-x-auto">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-3">
              Largest publicly disclosed short positions in Ambu
            </h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs uppercase tracking-wide text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">
                  <th className="pb-2 pr-3">Holder</th>
                  <th className="pb-2 text-right">Position</th>
                  <th className="pb-2 pl-3 text-right">Last changed</th>
                </tr>
              </thead>
              <tbody className="text-gray-700 dark:text-gray-300">
                {SHORT_HOLDERS.map((h) => (
                  <tr key={h.name} className="border-b border-gray-100 dark:border-gray-800">
                    <td className="py-2 pr-3">{h.name}</td>
                    <td className="py-2 text-right tabular-nums font-semibold text-red-600 dark:text-red-400">{h.value.toString()}%</td>
                    <td className="py-2 pl-3 text-right text-xs text-gray-500 dark:text-gray-400">{h.date}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-3 leading-relaxed">
              Source: The Danish FSA's register of major short positions via
              Zirium. Only positions above 0.5% are disclosed.
            </p>
          </div>

          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            The six positions together make up 4.0% of the share capital, just
            over half of the total short interest of 6.96%; the rest sits in
            positions below the 0.5% threshold. It is worth noting that both
            Millennium and AHL are classic multi-strategy hedge funds, while
            Wellington and BlackRock are primarily large asset managers, whose
            short positions typically come from their hedge fund or alternative
            products rather than their traditional long-only funds. The
            composition shows that the scepticism comes both from short-term
            traders and from long-term managers.
          </p>
        </section>

        {/* Section 7 */}
        <section className="mb-12">
          <SectionHeader n={7} title="Why does the stock keep falling?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            The paradox is clear: Operationally, Ambu is on track, but the
            stock has kept falling. There are five explanations that interact:
          </p>
          <ol className="space-y-3 text-gray-600 dark:text-gray-300 leading-relaxed list-decimal pl-6 mb-4">
            <li>
              <strong>The most recent growth disappointed.</strong>{" "}
              The Q2 results in May 2026 showed a slowdown to 7.3% organic
              growth and a downgrade of full-year guidance to 10-12%. When the
              multiple is still high, the market punishes any weakness in
              growth especially hard.
            </li>
            <li>
              <strong>Tariff and FX headwinds take the top off the margin uplift.</strong>{" "}
              The FY25/26 guidance is 12-14% EBIT margin versus earlier hopes
              of 14-16%. It is not a large difference, but it leads analysts to
              lower terminal values, and value-oriented investors hesitate to
              step in before there is clarity.
            </li>
            <li>
              <strong>The single-use conversion rate is slower than expected.</strong>{" "}
              Olympus' reusable endoscopes are deeply integrated into hospitals'
              workflows, and the transition to single-use equipment requires
              investment in monitors (aBox/aView) as well as clinical training.
              Even with well-documented infection-control and productivity
              advantages, adoption takes time.
            </li>
            <li>
              <strong>The valuation is still high.</strong>{" "}
              Even after the share price decline, Ambu trades at roughly 22x
              forward P/E and roughly 3x book value. For a margin story where
              the market is uncertain about sustainability in a tariff-ridden
              world, that is not yet cheap enough for value-oriented investors.
            </li>
            <li>
              <strong>The hedge funds have high short interest.</strong>{" "}
              6.96% short interest with big names like Wellington and
              Millennium means that the marginal buyer still meets a marginal
              seller who will short more on any price increase.
            </li>
          </ol>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            The market is not punishing the transformation. Instead it signals
            uncertainty about the durability of the margin uplift in a
            tariff-ridden world, and it is waiting for proof that single-use
            endoscopy genuinely becomes the standard in the number of
            procedures, not only in Ambu's product line.
          </p>
        </section>

        {/* Section 8 - Timeline */}
        <section className="mb-12">
          <SectionHeader n={8} title="Timeline of key events" />
          <div className="ml-2">
            <TimelineEvent date="May 2019" title="Management change: González replaces Marcher" color="#4361ee">
              <p>Lars Marcher is dismissed, and Juan José González takes over as CEO. He leads Ambu through the entire pandemic boom and the subsequent collapse.</p>
            </TimelineEvent>
            <TimelineEvent date="April 27, 2021" title="Pandemic peak: DKK 355.40" color="#4361ee">
              <p>The stock nearly tripled during the COVID boom and traded at a P/E well above 100 on trailing earnings.</p>
            </TimelineEvent>
            <TimelineEvent date="May 20, 2022" title="Britt Meelby Jensen takes office as CEO" color="#2a9d8f">
              <p>The board brings in Britt Meelby Jensen to lead the recovery after the boom-and-bust period.</p>
            </TimelineEvent>
            <TimelineEvent date="November 2022" title="ZOOM IN strategy launched" color="#4361ee">
              <p>Britt Meelby Jensen's three-year recovery strategy focused on restoring earnings and paying down debt.</p>
            </TimelineEvent>
            <TimelineEvent date="September 2025" title="ZOOM AHEAD announced" color="#4361ee">
              <p>New long-term targets toward FY29/30: organic growth of 11-13% CAGR and an EBIT margin of +20%.</p>
            </TimelineEvent>
            <TimelineEvent date="November 5, 2025" title="FY24/25 results: stock fell roughly 16%" color="#e63946">
              <p>Tariff costs and a weakened USD pressed the Q4 margin to 10.0%. For the full FY24/25, however, the EBIT margin landed at 13.0% and organic growth at 13.1%.</p>
            </TimelineEvent>
            <TimelineEvent date="April 29, 2026" title="Multi-year low: DKK 61.70" color="#e63946">
              <p>The lowest level since the autumn of 2022, roughly 81% below the pandemic peak.</p>
            </TimelineEvent>
            <TimelineEvent date="May 6, 2026" title="Q2 2025/26: growth slows, guidance lowered" color="#e63946">
              <p>Organic growth fell to 7.3%, and full-year guidance was lowered to 10-12%. At the same time, the board launched a buyback of up to DKK 300 million.</p>
            </TimelineEvent>
            <TimelineEvent date="May 7, 2026" title="Short interest peaks at 7.38%" color="#e63946">
              <p>The highest level over the period for which we have data.</p>
            </TimelineEvent>
          </div>
        </section>

        {/* Section 9 - For and against */}
        <section className="mb-12">
          <SectionHeader n={9} title="Arguments for and against" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            For investors, the case boils down to a trade-off between a real
            transformation and a series of headwinds:
          </p>
          <div className="grid sm:grid-cols-2 gap-4 mb-4">
            <div className="bg-blue-50 dark:bg-blue-500/10 rounded-2xl border border-blue-100 dark:border-blue-500/20 p-5">
              <h4 className="font-semibold text-blue-700 dark:text-blue-400 mb-3 text-sm uppercase tracking-wide">Positive factors</h4>
              <ul className="space-y-2 text-[15px] text-gray-700 dark:text-gray-300">
                <li className="flex gap-2"><span className="text-blue-400 mt-0.5">&#x25B2;</span>Operating margin nearly quintupled from 2.7% to 13.0%</li>
                <li className="flex gap-2"><span className="text-blue-400 mt-0.5">&#x25B2;</span>Organic growth of 13.1% in the most recent fiscal year</li>
                <li className="flex gap-2"><span className="text-blue-400 mt-0.5">&#x25B2;</span>Net cash position of DKK 319 million</li>
                <li className="flex gap-2"><span className="text-blue-400 mt-0.5">&#x25B2;</span>Endoscopy Solutions grew 13.8% in Q2</li>
                <li className="flex gap-2"><span className="text-blue-400 mt-0.5">&#x25B2;</span>ZOOM AHEAD targets +20% EBIT margin toward FY29/30</li>
                <li className="flex gap-2"><span className="text-blue-400 mt-0.5">&#x25B2;</span>Buyback of up to DKK 300 million under way</li>
              </ul>
            </div>
            <div className="bg-red-50 dark:bg-red-500/10 rounded-2xl border border-red-100 dark:border-red-500/20 p-5">
              <h4 className="font-semibold text-red-700 dark:text-red-400 mb-3 text-sm uppercase tracking-wide">Negative factors</h4>
              <ul className="space-y-2 text-[15px] text-gray-700 dark:text-gray-300">
                <li className="flex gap-2"><span className="text-red-400 mt-0.5">&#x25BC;</span>Organic growth slowed to 7.3% in Q2, guidance lowered to 10-12%</li>
                <li className="flex gap-2"><span className="text-red-400 mt-0.5">&#x25BC;</span>Anaesthesia &amp; Patient Monitoring fell 2.5%</li>
                <li className="flex gap-2"><span className="text-red-400 mt-0.5">&#x25BC;</span>Tariff and FX headwinds: margin guided 12-14% versus hopes of 14-16%</li>
                <li className="flex gap-2"><span className="text-red-400 mt-0.5">&#x25BC;</span>High short interest (6.96%, peak 7.38%)</li>
                <li className="flex gap-2"><span className="text-red-400 mt-0.5">&#x25BC;</span>Valuation still high (roughly 22x forward P/E)</li>
                <li className="flex gap-2"><span className="text-red-400 mt-0.5">&#x25BC;</span>Slow single-use conversion in GI</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Section 10 - Conclusion */}
        <section className="mb-12">
          <SectionHeader n={10} title="Conclusion" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            Ambu is the interesting paradox on the Danish stock exchange: A
            company that has operationally done almost everything right under
            new management, but whose stock keeps falling. The EBIT margin has
            nearly quintupled (from 2.7% to 13.0%), net debt has been
            eliminated, and the strategy is clear with ambitious FY29/30
            targets.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            The flip side is that the market is currently pricing the tariff
            pressure, the slow adoption of single-use equipment and a high
            valuation more harshly than the achieved transformation. The hedge
            funds' short interest at a historic high is the clearest signal
            that the professional investor base does not believe in a quick
            comeback.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            For investors, Ambu is a case about timing. The fundamental story
            is not broken, but the share price reflects a world where tariffs,
            currency and competitive friction take longer to work through than
            the market had hoped. If Ambu delivers both the margin and the
            growth targets in ZOOM AHEAD toward FY29/30, today's price may
            prove attractive in hindsight. If the tariffs normalise more
            slowly, or the adoption of single-use equipment disappoints, the
            stock may continue down. The ongoing buyback of DKK 300 million may
            put a short-term floor under the stock, but does not resolve the
            growth question. That is the balance investors must weigh.
          </p>
        </section>

        {/* Feedback widget */}
        <FeedbackWidget pageType="analysis" pageId={SLUG} />

        {/* Related */}
        <RelatedAnalyses currentSlug={SLUG} />

        {/* Disclaimer */}
        <footer className="border-t border-gray-100 dark:border-gray-800 pt-6">
          <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed text-center">
            <strong>Sources:</strong> Yahoo Finance via yfinance (stock and
            index returns), Ambu annual reports and press releases (operating
            margin, ZOOM IN/AHEAD strategy), the Danish FSA's register of major
            short positions via Zirium.{" "}
            <strong>Disclaimer:</strong>{" "}
            This analysis is for informational purposes only and does not
            constitute investment advice. Past performance is not a guarantee
            of future returns. Always do your own analysis and seek
            professional advice before trading.
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-400 text-center mt-3">
            Copyright Zirium  |  June 1, 2026
          </p>
        </footer>
      </article>
    </PageTemplate>
  );
};

export default AmbuAnalysisPageEn;
