import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import PageTemplate from "../components/PageTemplate";
import RelatedAnalyses from "../components/RelatedAnalyses";
import FeedbackWidget from "../components/FeedbackWidget";
import { trackPageView } from "../analytics";
import { HOST } from "../apis/ShortPositionAPI";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine,
} from "recharts";

const SLUG = "ambu/2026-05-28";

// ─── types ───────────────────────────────────────────────────────────────────
interface ComparisonPoint {
  date: string;
  ambu: number;
  olympus: number;
  bsx: number;
  colo: number;
  isrg: number;
}

interface MarginPoint {
  fy: string;
  margin: number;
}

interface ShortHolder {
  name: string;
  value: number;
  date: string;
}

// ─── static data ────────────────────────────────────────────────────────────
// Generated by yfinance daily close, last trading day of month, normalised to 100.
// Window: 2021-05 → 2026-05.
const COMPARISON_DATA: ComparisonPoint[] = [
  { date: "2021-05", ambu: 100.0, olympus: 100.0, bsx: 100.0, colo: 100.0, isrg: 100.0 },
  { date: "2021-06", ambu: 106.2, olympus: 93.9, bsx: 100.5, colo: 107.1, isrg: 109.2 },
  { date: "2021-07", ambu: 102.2, olympus: 95.5, bsx: 107.2, colo: 119.4, isrg: 117.7 },
  { date: "2021-08", ambu: 87.7, olympus: 98.3, bsx: 106.1, colo: 113.6, isrg: 125.1 },
  { date: "2021-09", ambu: 83.6, olympus: 104.5, bsx: 102.0, colo: 104.8, isrg: 118.0 },
  { date: "2021-10", ambu: 80.7, olympus: 104.7, bsx: 101.4, colo: 109.2, isrg: 128.6 },
  { date: "2021-11", ambu: 81.9, olympus: 108.0, bsx: 89.5, colo: 111.7, isrg: 115.5 },
  { date: "2021-12", ambu: 76.2, olympus: 112.7, bsx: 99.8, colo: 119.8, isrg: 128.0 },
  { date: "2022-01", ambu: 61.3, olympus: 108.3, bsx: 100.8, colo: 99.8, isrg: 101.2 },
  { date: "2022-02", ambu: 54.1, olympus: 97.8, bsx: 103.8, colo: 103.9, isrg: 103.4 },
  { date: "2022-03", ambu: 44.1, olympus: 99.5, bsx: 104.1, colo: 106.7, isrg: 107.5 },
  { date: "2022-04", ambu: 41.6, olympus: 98.2, bsx: 99.0, colo: 99.8, isrg: 85.2 },
  { date: "2022-05", ambu: 41.8, olympus: 114.4, bsx: 96.4, colo: 85.8, isrg: 81.1 },
  { date: "2022-06", ambu: 30.4, olympus: 116.0, bsx: 87.6, colo: 84.2, isrg: 71.5 },
  { date: "2022-07", ambu: 36.3, olympus: 119.9, bsx: 96.5, colo: 88.4, isrg: 82.0 },
  { date: "2022-08", ambu: 32.9, olympus: 128.0, bsx: 94.7, colo: 88.3, isrg: 73.3 },
  { date: "2022-09", ambu: 29.3, olympus: 118.2, bsx: 91.0, colo: 80.8, isrg: 66.8 },
  { date: "2022-10", ambu: 37.2, olympus: 133.6, bsx: 101.3, colo: 87.4, isrg: 87.8 },
  { date: "2022-11", ambu: 39.1, olympus: 119.4, bsx: 106.4, colo: 86.8, isrg: 96.3 },
  { date: "2022-12", ambu: 39.2, olympus: 100.0, bsx: 108.7, colo: 84.5, isrg: 94.5 },
  { date: "2023-01", ambu: 41.4, olympus: 103.3, bsx: 108.7, colo: 85.6, isrg: 87.5 },
  { date: "2023-02", ambu: 45.5, olympus: 97.6, bsx: 109.8, colo: 84.7, isrg: 81.7 },
  { date: "2023-03", ambu: 45.3, olympus: 98.6, bsx: 117.6, colo: 93.9, isrg: 91.0 },
  { date: "2023-04", ambu: 47.2, olympus: 100.7, bsx: 122.5, colo: 101.3, isrg: 107.3 },
  { date: "2023-05", ambu: 48.1, olympus: 90.1, bsx: 121.0, colo: 91.3, isrg: 109.7 },
  { date: "2023-06", ambu: 49.2, olympus: 96.4, bsx: 127.1, colo: 88.8, isrg: 121.8 },
  { date: "2023-07", ambu: 44.1, olympus: 98.5, bsx: 121.9, colo: 87.7, isrg: 115.6 },
  { date: "2023-08", ambu: 36.8, olympus: 83.8, bsx: 126.8, colo: 81.7, isrg: 111.4 },
  { date: "2023-09", ambu: 32.5, olympus: 82.6, bsx: 124.1, colo: 77.8, isrg: 104.1 },
  { date: "2023-10", ambu: 30.6, olympus: 85.0, bsx: 120.3, colo: 76.5, isrg: 93.4 },
  { date: "2023-11", ambu: 41.0, olympus: 92.1, bsx: 131.4, colo: 84.1, isrg: 110.7 },
  { date: "2023-12", ambu: 46.3, olympus: 86.8, bsx: 135.9, colo: 80.4, isrg: 120.2 },
  { date: "2024-01", ambu: 50.6, olympus: 93.6, bsx: 148.7, colo: 83.0, isrg: 134.7 },
  { date: "2024-02", ambu: 53.1, olympus: 90.7, bsx: 155.6, colo: 95.3, isrg: 137.4 },
  { date: "2024-03", ambu: 50.0, olympus: 94.2, bsx: 161.0, colo: 97.1, isrg: 142.2 },
  { date: "2024-04", ambu: 49.6, olympus: 93.6, bsx: 168.9, colo: 88.1, isrg: 132.0 },
  { date: "2024-05", ambu: 57.9, olympus: 105.2, bsx: 177.6, colo: 85.9, isrg: 143.2 },
  { date: "2024-06", ambu: 59.0, olympus: 110.3, bsx: 181.0, colo: 87.1, isrg: 158.5 },
  { date: "2024-07", ambu: 61.7, olympus: 110.8, bsx: 173.6, colo: 93.3, isrg: 158.4 },
  { date: "2024-08", ambu: 56.4, olympus: 113.1, bsx: 192.2, colo: 95.8, isrg: 175.5 },
  { date: "2024-09", ambu: 57.8, olympus: 115.6, bsx: 196.9, colo: 91.1, isrg: 175.0 },
  { date: "2024-10", ambu: 55.9, olympus: 115.3, bsx: 197.5, colo: 89.0, isrg: 179.5 },
  { date: "2024-11", ambu: 48.9, olympus: 100.4, bsx: 213.1, colo: 92.6, isrg: 193.1 },
  { date: "2024-12", ambu: 45.8, olympus: 100.8, bsx: 209.9, colo: 81.8, isrg: 185.9 },
  { date: "2025-01", ambu: 59.4, olympus: 100.7, bsx: 240.6, colo: 86.4, isrg: 203.7 },
  { date: "2025-02", ambu: 57.9, olympus: 87.1, bsx: 243.9, colo: 79.5, isrg: 204.2 },
  { date: "2025-03", ambu: 52.0, olympus: 82.8, bsx: 237.1, colo: 75.3, isrg: 176.4 },
  { date: "2025-04", ambu: 51.9, olympus: 79.3, bsx: 241.8, colo: 77.2, isrg: 183.7 },
  { date: "2025-05", ambu: 44.6, olympus: 78.9, bsx: 247.4, colo: 66.2, isrg: 196.8 },
  { date: "2025-06", ambu: 43.8, olympus: 72.9, bsx: 252.4, colo: 62.6, isrg: 193.6 },
  { date: "2025-07", ambu: 42.4, olympus: 77.1, bsx: 246.6, colo: 62.8, isrg: 171.4 },
  { date: "2025-08", ambu: 42.4, olympus: 73.3, bsx: 247.9, colo: 63.8, isrg: 168.6 },
  { date: "2025-09", ambu: 40.8, olympus: 79.6, bsx: 229.4, colo: 56.5, isrg: 159.3 },
  { date: "2025-10", ambu: 44.4, olympus: 80.8, bsx: 236.7, colo: 61.0, isrg: 190.3 },
  { date: "2025-11", ambu: 38.5, olympus: 89.3, bsx: 238.7, colo: 60.5, isrg: 204.3 },
  { date: "2025-12", ambu: 38.8, olympus: 84.4, bsx: 224.1, colo: 56.9, isrg: 201.7 },
  { date: "2026-01", ambu: 37.5, olympus: 78.3, bsx: 219.8, colo: 55.8, isrg: 179.6 },
  { date: "2026-02", ambu: 35.0, olympus: 65.0, bsx: 180.6, colo: 50.8, isrg: 179.4 },
  { date: "2026-03", ambu: 30.1, olympus: 63.3, bsx: 147.5, colo: 45.4, isrg: 164.2 },
  { date: "2026-04", ambu: 27.8, olympus: 65.8, bsx: 135.4, colo: 41.0, isrg: 163.0 },
  { date: "2026-05", ambu: 28.9, olympus: 78.5, bsx: 115.7, colo: 41.4, isrg: 150.5 },
];

// Operating margin per regnskabsår (Ambu's fiskaler slutter september)
// FY20/21 til FY23/24 fra yfinance Total Revenue / Operating Income.
// FY24/25 fra Ambu Interim Report Q4 2024/25 (5. november 2025): EBIT b.s.i. 13,0%.
const MARGIN_DATA: MarginPoint[] = [
  { fy: "FY20/21", margin: 8.5 },
  { fy: "FY21/22", margin: 2.7 },
  { fy: "FY22/23", margin: 6.3 },
  { fy: "FY23/24", margin: 12.0 },
  { fy: "FY24/25", margin: 13.0 },
];

// Aktuelle large short-positioner i Ambu (Zirium's egen database, 27. maj 2026)
const SHORT_HOLDERS: ShortHolder[] = [
  { name: "Wellington Management International Limited", value: 0.82, date: "14. maj 2026" },
  { name: "Millennium International Management LP",      value: 0.80, date: "27. maj 2026" },
  { name: "AHL Partners LLP",                            value: 0.70, date: "4. maj 2026" },
  { name: "J.P. Morgan Asset Management (UK) Limited",   value: 0.68, date: "6. nov 2025" },
  { name: "BlackRock Financial Management, Inc.",        value: 0.50, date: "1. maj 2026" },
  { name: "BlackRock Advisors, LLC",                     value: 0.50, date: "23. apr 2026" },
];

// ─── helpers ─────────────────────────────────────────────────────────────────
const formatDate = (ym: string): string => {
  const [y, m] = ym.split("-");
  const months = ["jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec"];
  return `${months[parseInt(m, 10) - 1]} ${y.slice(2)}`;
};

// ─── sub-components ──────────────────────────────────────────────────────────
function KPI({ value, label, highlight, tone = "blue" }: { value: string; label: string; highlight?: boolean; tone?: "blue" | "red" | "green" }) {
  const toneClasses = {
    blue:  { bg: "bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800",       text: "text-blue-600 dark:text-blue-400" },
    red:   { bg: "bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800",           text: "text-red-700 dark:text-red-400" },
    green: { bg: "bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800", text: "text-emerald-700 dark:text-emerald-400" },
  };
  const t = toneClasses[tone];
  return (
    <div className={`rounded-2xl border p-4 sm:p-5 text-center ${highlight ? t.bg : "bg-white dark:bg-[#19191f] border-gray-100 dark:border-gray-800"}`}>
      <p className={`text-lg sm:text-xl font-bold tabular-nums ${highlight ? t.text : "text-gray-900 dark:text-white"}`}>{value}</p>
      <p className="text-xs text-gray-500 dark:text-gray-300 mt-1 leading-tight">{label}</p>
    </div>
  );
}

function SectionHeader({ n, title }: { n: number; title: string }) {
  return (
    <h2 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-4">
      {n}. {title}
    </h2>
  );
}

// ─── main page ───────────────────────────────────────────────────────────────
const AmbuAnalysisPage: React.FC = () => {
  const navigate = useNavigate();

  useEffect(() => {
    trackPageView(`/analyse/${SLUG}`, "Ambu analyse");
    fetch(`${HOST}/stats/visit/ambu-analysis/`).catch(() => {});
  }, []);

  return (
    <PageTemplate>
      <title>Ambu: 5 års fald trods en succesfuld transformation | Zirium</title>
      <meta
        name="description"
        content="Ambu er faldet 71% over 5 år. Operationelt har selskabet gennemført en stærk transformation under CEO Britt Meelby Jensen med margin der er firedoblet. Men aktien bliver ved at falde. Vi ser på paradokset, tariff-presset og hedgefondenes rekordhøje shortinteresse."
      />
      <meta property="og:title" content="Ambu: 5 års fald trods en succesfuld transformation" />
      <meta property="og:description" content="Ambu -71% over 5 år trods firedoblet margin. Hedgefonde har historisk høj shortinteresse. Hvad er paradokset?" />
      <meta property="og:type" content="article" />
      <meta property="og:url" content={`https://www.zirium.dk/analyse/${SLUG}`} />
      <meta property="og:image" content="https://www.zirium.dk/og-images/ambu-2026-05-28.png" />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:type" content="image/png" />
      <meta property="og:site_name" content="Zirium" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Ambu: 5 års fald trods en succesfuld transformation" />
      <meta name="twitter:description" content="Ambu -71% over 5 år trods firedoblet margin. Hedgefonde har historisk høj shortinteresse." />
      <meta name="twitter:image" content="https://www.zirium.dk/og-images/ambu-2026-05-28.png" />
      <script type="application/ld+json">{JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "Ambu: 5 års fald trods en succesfuld transformation",
        "description": "Ambu er faldet 71% over 5 år. Operationelt har selskabet gennemført en stærk transformation, men aktien fortsætter ned.",
        "author": { "@type": "Person", "name": "Araz Bayat Makoo" },
        "publisher": { "@type": "Organization", "name": "Zirium", "url": "https://www.zirium.dk" },
        "datePublished": "2026-05-28",
        "mainEntityOfPage": `https://www.zirium.dk/analyse/${SLUG}`,
        "inLanguage": "da",
      })}</script>

      <article className="w-full max-w-[900px] mx-auto px-5 sm:px-8 pb-10 sm:pb-16">
        <button
          className="text-blue-600 hover:text-blue-700 bg-transparent border-none text-base inline-flex items-center gap-1.5 focus:ring-2 focus:ring-blue-300 rounded-sm min-h-[44px] min-w-[44px]"
          onClick={() => {
            if (window.history.length > 1 && window.history.state?.idx > 0) {
              navigate(-1);
            } else {
              navigate("/analyse");
            }
          }}
        >
          <span aria-hidden="true">←</span>
          Tilbage
        </button>

        {/* Header */}
        <header className="mb-10 mt-4">
          <p className="text-base text-gray-600 dark:text-gray-300 mb-4">
            Analyse lavet af Araz Bayat Makoo (Zirium) - 28. maj 2026
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-gray-900 dark:text-white mb-3 leading-tight">
            Ambu: 5 års fald trods en succesfuld transformation
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 leading-relaxed">
            Ambu A/S (AMBU-B)
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Ambu er faldet cirka 71% siden maj 2021 og handler i dag omkring
            66,80 DKK mod en pandemi-top på 355,40 DKK den 27. april 2021. Det
            er et fald på 81% fra toppen, og aktien ramte en ny all-time low
            på 61,70 DKK så sent som den 29. april 2026.
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Den primære årsag til faldet er ikke operationel svaghed, men en
            uundgåelig værdiansættelses-reset fra et boble-niveau. I
            september 2020 ramte Ambus P/E-multipel 3.730x på rullende
            indtjening, og selv på normaliserede 2021-tal handlede aktien
            over 100x indtjening. Den slags værdiansættelser har historisk
            kun ét udfald: Et hårdt mean-reversion-fald uanset selskabets
            operationelle udvikling.
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Det paradoksale er, at selskabet operationelt har gennemført en
            af de stærkeste transformationer i dansk sundhedssektor under
            CEO Britt Meelby Jensen. EBIT-marginen før special items er
            næsten femdoblet fra 2,7% i FY21/22 til 13,0% i FY24/25, organisk
            omsætningsvækst landede på 13,1% i seneste hele regnskabsår, og
            selskabet har nu netto-kontant-position. Alligevel fortsætter
            aktien ned. Hvad gør den ikke?
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Vi gennemgår 5-års-kursen sammenlignet med konkurrenterne,
            transformationen under ZOOM IN-strategien, den nye ZOOM AHEAD-plan
            mod FY29/30, det aktuelle tariff-pres og hedgefondenes historisk
            høje shortinteresse i selskabet.
          </p>
        </header>

        {/* KPIs */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-12">
          <KPI value="-71%" label="5-års afkast" highlight tone="red" />
          <KPI value="-34%" label="1-års afkast" />
          <KPI value="-81%" label="Fra all-time high" />
          <KPI value="7,21%" label="Short interest (27/5)" highlight tone="red" />
        </div>

        {/* Section 1 */}
        <section className="mb-12">
          <SectionHeader n={1} title="Hvor stort er problemet egentlig?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Ambu er klart den værst-performende sammenlignelige medical
            device-aktie over 5 år. Sammenligningen viser, at det ikke er en
            bred krise i sektoren: Boston Scientific er steget cirka 16% og
            Intuitive Surgical cirka 51% i samme periode, mens japanske
            Olympus (den klare reusable-konkurrent) "kun" er faldet 22%.
            Tættere på hjemmemarkedet har Coloplast tabt 59%, hvilket viser,
            at danske defensive sundhedsaktier samlet har været under pres,
            men Ambu har leveret det største fald.
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Graf: Sammenligning af Ambu vs Olympus, Boston Scientific, Coloplast og Intuitive Surgical over 5 år">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Ambu vs. 4 medical device-peers (maj 2021 = 100)</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Månedsslut, prisindeks (uden udbytter), lokal valuta</p>
            <ResponsiveContainer width="100%" height={320}>
              <LineChart data={COMPARISON_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis
                  dataKey="date"
                  tick={{ fontSize: 11, fill: "#6b7280" }}
                  tickFormatter={formatDate}
                  interval={11}
                />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} domain={[20, 260]} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => Number(v).toFixed(1)}
                  labelFormatter={(label) => formatDate(String(label))}
                />
                <Legend wrapperStyle={{ fontSize: 12 }} />
                <ReferenceLine y={100} stroke="#9ca3af" strokeDasharray="3 3" />
                <Line type="monotone" dataKey="isrg" name="Intuitive Surgical" stroke="#10b981" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="bsx" name="Boston Scientific" stroke="#3b82f6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="olympus" name="Olympus" stroke="#f59e0b" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="colo" name="Coloplast" stroke="#8b5cf6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="ambu" name="Ambu" stroke="#ef4444" strokeWidth={3} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>

          <p className="text-xs text-gray-500 dark:text-gray-400 italic leading-relaxed">
            Note: Sammenligningen bruger prisindekser uden reinvesterede
            udbytter for at sikre sammenlignelighed. Afkast er målt i lokal
            valuta og er ikke valuta-justeret. For Olympus betyder JPY-DKK
            depreciation, at en dansk investor reelt har haft et lidt større
            fald end de 22% prisindekset viser.
          </p>
        </section>

        {/* Section 2 */}
        <section className="mb-12">
          <SectionHeader n={2} title="Pandemi-eufori, boble-værdiansættelse og kollaps" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Ambus toppris på 355,40 DKK den 27. april 2021 var et resultat
            af en perfekt storm under COVID-19. Engangsendoskoper, som var
            Ambus kerneprodukt, blev pludselig set som en smitterisiko-løsning,
            fordi reusable instrumenter krævede genbrugsprocessering der
            blev anset som en risikofaktor under pandemien. Hospitalerne
            købte massivt og opbyggede lagre langt over normal forbrugsrate.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Den kombinerede effekt var dramatisk på både regnskaber og
            værdiansættelse. Aktien næsten tredoblede sig fra 2019 til april
            2021, og markedet priste Ambu som om engangsendoskoper-paradigmet
            var ved at overtage hele endoskopi-markedet på få år. I september
            2020 ramte P/E-multiplen 3.730x på rullende 12 måneders indtjening,
            et niveau der historisk har været forbeholdt "story stocks" i
            ekstreme boble-toppe. Selv på normaliserede 2021-tal handlede
            aktien på over 100x indtjening.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Det betyder, at en stor del af Ambus efterfølgende fald ikke var
            en operationel kritik, men en uundgåelig værdiansættelses-reset.
            Selv hvis indtjeningen havde holdt sig konstant, ville et fald i
            multiplen fra 100x til 25x have halveret aktien tre gange. Da
            indtjeningen samtidig kollapsede (EBIT-margin fra 8,5% til 2,7%
            på et regnskabsår), blev nedturen forstærket.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Til den interne corporate governance-historik hører også Lars
            Marcher-sagen fra maj 2019, hvor den fyrede CEO sad med 3,8 mio.
            aktier privat og nægtede at oplyse om han solgte efter fyringen,
            hvor offentliggørelseskravet ikke længere gjaldt. Dansk
            Aktionærforening kritiserede dette som et regelhul. Episoden er
            ikke direkte årsag til faldet siden 2021, men den prægede en
            periode hvor mange institutionelle investorer blev forsigtige med
            Ambu som ledelses-case.
          </p>
        </section>

        {/* Section 3 */}
        <section className="mb-12">
          <SectionHeader n={3} title="ZOOM IN: Britt Meelby Jensens omstilling" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Britt Meelby Jensen tiltrådte som CEO den 20. maj 2022. Hun kom
            med en sjælden kombination af baggrunde: CEO for Atos Medical
            (medical device) frem til at hun solgte selskabet til Coloplast
            i begyndelsen af 2022, og før det CEO for Zealand Pharma fra 2015
            til 2019. Hun forstår både medical device-kommerciel ekspansion
            og pharma-pipeline-eksekvering.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            I november 2022 lancerede hun ZOOM IN-strategien med tre klare
            målsætninger: Genskab finansielle fundamenter, gennemfør strategisk
            fokusering, og afvikl gæld. Strategien blev eksekveret over tre
            år frem mod 2025. Tabellen viser margin-progressionen klart:
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Graf: Ambu's operating margin progression FY21 til FY24">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Ambu operating margin per regnskabsår</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Margin (%) per fiskalt år (slutter 30. september). Kilde: Ambu annual reports.</p>
            <ResponsiveContainer width="100%" height={260}>
              <BarChart data={MARGIN_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis dataKey="fy" tick={{ fontSize: 11, fill: "#6b7280" }} />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} tickFormatter={(v) => `${v}%`} domain={[0, 18]} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => `${Number(v).toFixed(1).replace(".", ",")}%`}
                />
                <Bar dataKey="margin" name="EBIT margin" fill="#2563eb" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Marginen er næsten femdoblet fra 2,7% til 13,0% over fire
            regnskabsår. I FY24/25 (afsluttet 30. september 2025) leverede
            Ambu organisk omsætningsvækst på 13,1%, free cash flow før opkøb
            på 407 mio. DKK, og selskabet endte med netto-kontant-position
            på 319 mio. DKK. Bestyrelsen har samtidig vedtaget at returnere
            260 mio. DKK til aktionærerne via udbytte (110 mio. DKK) og
            aktietilbagekøb (150 mio. DKK). Operationelt er transformationen
            reel og bekræftet i de officielle tal.
          </p>
        </section>

        {/* Section 4 */}
        <section className="mb-12">
          <SectionHeader n={4} title="ZOOM AHEAD: nye ambitioner mod FY29/30" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            I september 2025 annoncerede Ambu opfølgningsstrategien ZOOM
            AHEAD, der hæver de langsigtede mål. For FY29/30 har Ambu nu
            følgende officielle mål:
          </p>
          <ul className="space-y-2 text-gray-600 dark:text-gray-300 leading-relaxed list-disc pl-6 mb-4">
            <li><strong>Organisk omsætningsvækst 11-13% CAGR</strong> (op fra +10% mod FY27/28)</li>
            <li><strong>Endoscopy Solutions: 15-20% CAGR</strong> som vækst-motor</li>
            <li><strong>Anaesthesia &amp; Patient Monitoring: 3-5% CAGR</strong> som stabil base</li>
            <li><strong>EBIT-margin på +20%</strong> (samme niveau som tidligere FY27/28-mål)</li>
            <li><strong>Cash conversion på +40%</strong> (FCF før opkøb / EBITDA)</li>
          </ul>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Endoscopy Solutions er omdrejningspunktet og indeholder
            kerneproduktlinjen aScope. Senest har Ambu lanceret aScope 5
            Broncho (top-tier bronkoskop), aScope Gastro Large (4,2 mm
            arbejdskanal til avancerede GI-procedurer) og er ved at udvikle
            en koloskopilinje. Strategien handler om at omsætte single-use
            paradigmet til markeder, hvor Olympus' reusable-instrumenter
            stadig dominerer.
          </p>
        </section>

        {/* Section 5 */}
        <section className="mb-12">
          <SectionHeader n={5} title="Tariff-presset der ramte i 2025" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Den 5. november 2025 rapporterede Ambu deres FY24/25-regnskab,
            og aktien faldt cirka 13% på dagen. Årsagen var ikke svag drift,
            men en kombination af tariff-omkostninger og valutamodvind. Q4
            FY24/25 (kvartalet juli til september 2025) leverede en
            EBIT-margin før special items på 10,0% mod konsensus omkring
            12-13%. Tariff-effekten og en svækket USD over for DKK var
            hovedansvarlige.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Trump-administrationens tariffer på medicinske produkter
            produceret uden for USA ramte Ambu særligt hårdt, fordi Ambus
            primære produktionscentre ligger i Malaysia og Mexico. Selskabet
            har annonceret en plan om at flytte hele den nordamerikanske
            endoskopi-efterspørgsel til lokal produktion inden FY29/30, men
            indtil da må Ambu absorbere omkostningerne.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            For FY25/26 har Ambu guidet organisk omsætningsvækst på 10-13%
            og EBIT-margin før special items på 12-14% (14-16% eksklusive
            tariff-impacten på cirka 2 procentpoint). Det er den primære
            grund til at marginerne falder kortvarigt efter at have toppet
            på 16,1% i Q1 FY24/25 (kvartalet oktober-december 2024).
          </p>
        </section>

        {/* Section 6 */}
        <section className="mb-12">
          <SectionHeader n={6} title="Hedgefondenes rekordhøje shortinteresse" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Den 27. maj 2026 stod den samlede shortinteresse i Ambu på 7,21%
            af aktiekapitalen. Toppen på 7,38% blev nået den 7. maj 2026,
            kun tre uger før denne analyse. Det er det højeste niveau Ambu
            har haft i Finanstilsynets registreringer, og det signalerer at
            institutionelle investorer er fundamentalt skeptiske over for
            ZOOM AHEAD-targetene.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            De største offentligt registrerede short-positioner kommer fra
            en blanding af multi-strategy hedgefonde og store kapitalforvaltere:
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-4 sm:p-5 mb-4 overflow-x-auto">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-3">
              Største offentligt registrerede short-positioner i Ambu
            </h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs uppercase tracking-wide text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">
                  <th className="pb-2 pr-3">Holder</th>
                  <th className="pb-2 text-right">Position</th>
                  <th className="pb-2 pl-3 text-right">Senest ændret</th>
                </tr>
              </thead>
              <tbody className="text-gray-700 dark:text-gray-300">
                {SHORT_HOLDERS.map((h) => (
                  <tr key={h.name} className="border-b border-gray-100 dark:border-gray-800">
                    <td className="py-2 pr-3">{h.name}</td>
                    <td className="py-2 text-right tabular-nums font-semibold text-red-600 dark:text-red-400">{h.value.toString().replace(".", ",")}%</td>
                    <td className="py-2 pl-3 text-right text-xs text-gray-500 dark:text-gray-400">{h.date}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-3 leading-relaxed">
              Kilde: Finanstilsynets register over store korte positioner via
              Zirium. Kun positioner over 0,5% offentliggøres.
            </p>
          </div>

          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Det er værd at notere, at både Millennium og AHL er klassiske
            multi-strategy hedgefonde, mens Wellington og BlackRock primært
            er store kapitalforvaltere, hvis short-positioner typisk kommer
            fra deres hedgefond- eller alternative produkter snarere end
            deres traditionelle long-only-fonde. Sammensætningen viser at
            skepsissen kommer både fra kortsigtede traders og fra langsigtede
            forvaltere.
          </p>
        </section>

        {/* Section 7 */}
        <section className="mb-12">
          <SectionHeader n={7} title="Hvorfor bliver aktien ved at falde?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Paradokset er klart: Operationelt er Ambu på sporet, men aktien
            har fortsat ned. Der er fire forklaringer der spiller sammen:
          </p>
          <ol className="space-y-3 text-gray-600 dark:text-gray-300 leading-relaxed list-decimal pl-6 mb-4">
            <li>
              <strong>Tariff- og FX-modvind tager toppen af margin-løftet.</strong>{" "}
              FY25/26-vejledningen er 12-14% EBIT-margin mod tidligere håb
              om 14-16%. Det er ikke en stor forskel, men det får analytikere
              til at justere terminalværdier ned, og value-investorerne
              tøver med at træde ind før der er klarhed.
            </li>
            <li>
              <strong>Single-use konverteringsraten er langsommere end forventet.</strong>{" "}
              Olympus' reusable-endoskoper er dybt integrerede i hospitalers
              workflows, og overgangen til single-use kræver investering i
              displays (aBox/aView) samt klinisk uddannelse. Selv med
              veldokumenterede smitte- og produktivitetsfordele tager
              adoption tid.
            </li>
            <li>
              <strong>Værdiansættelsen er stadig rig på faldende business.</strong>{" "}
              Ambu handler til cirka 21x forward P/E og 2,8x P/B med
              omsætningsvækst på cirka 1,2% år-over-år (seneste rapporterede
              kvartal). For investorer der køber multipler frem for vækst,
              er det ikke billigt nok endnu.
            </li>
            <li>
              <strong>Hedgefondene har rekordhøj shortinteresse.</strong>{" "}
              7,21% short interest med store navne som Wellington og
              Millennium betyder, at den marginale køber stadig møder en
              marginal sælger der vil shorte mere ved enhver bounce.
            </li>
          </ol>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Markedet straffer ikke transformationen. Det signalerer i stedet
            usikkerhed om holdbarheden af margin-løftet i en tariff-præget
            verden, og det venter på bevis for at single-use endoscopy reelt
            bliver standarden i procedure-volumen, ikke kun i Ambus
            produktlinje.
          </p>
        </section>

        {/* Section 8 */}
        <section className="mb-12">
          <SectionHeader n={8} title="Konklusion" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            Ambu er den interessante kontradiktion på dansk børs: Et selskab
            der operationelt har gjort næsten alt rigtigt under ny ledelse,
            men hvor aktien fortsætter med at falde. EBIT-marginen er
            firedoblet, gælden er afviklet, og strategien er klar med
            ambitiøse FY29/30-mål.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            Modsiden er, at markedet pt. priser tariff-presset, langsom
            single-use adoption og rig værdiansættelse hårdere end den
            opnåede transformation. Hedgefondenes shortinteresse på et
            historisk topniveau er det tydeligste signal om at den
            professionelle investorbase ikke tror på et hurtigt comeback.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            For investorer er Ambu en case om timing. Den fundamentale
            historie er ikke gået i stykker, men aktiekursen reflekterer en
            verden hvor tariffer, valuta og konkurrence-friktion tager
            længere tid at arbejde sig igennem end markedet havde håbet.
            Hvis ZOOM AHEAD leverer +20% EBIT-margin mod FY29/30, vil
            dagens kurs vise sig at være meget billig. Hvis tarifferne
            normaliseres langsommere eller single-use adoptionsraten skuffer,
            kan aktien fortsætte ned. Det er den balance investorer må veje.
          </p>
        </section>

        {/* Feedback widget */}
        <FeedbackWidget pageType="analysis" pageId={SLUG} />

        {/* Related */}
        <RelatedAnalyses currentSlug={SLUG} />

        {/* Disclaimer */}
        <footer className="border-t border-gray-100 dark:border-gray-800 pt-6">
          <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed text-center">
            <strong>Kilder:</strong> Yahoo Finance via yfinance (aktie- og
            indeks-afkast), Ambu annual reports og pressemeddelelser
            (operating margin, ZOOM IN/AHEAD-strategi), Finanstilsynets
            register over store korte positioner via Zirium.{" "}
            <strong>Ansvarsfraskrivelse:</strong>{" "}
            Denne analyse er alene til informationsformål og udgør ikke
            investeringsrådgivning. Historisk afkast er ikke en garanti for
            fremtidigt afkast. Foretag altid din egen analyse, og søg
            professionel rådgivning før du handler.
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-400 text-center mt-3">
            Copyright Zirium  |  28. maj 2026
          </p>
        </footer>
      </article>
    </PageTemplate>
  );
};

export default AmbuAnalysisPage;
