import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import PageTemplate from "../components/PageTemplate";
import RelatedAnalyses from "../components/RelatedAnalyses";
import FeedbackWidget from "../components/FeedbackWidget";
import { trackPageView } from "../analytics";
import { HOST } from "../apis/ShortPositionAPI";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine,
} from "recharts";

const SLUG = "ambu/2026-06-01";

// ─── types ───────────────────────────────────────────────────────────────────
interface ComparisonPoint {
  date: string;
  ambu: number;
  olympus: number;
  bsx: number;
  colo: number;
  isrg: number;
}

interface MarginPoint {
  fy: string;
  margin: number;
}

interface ShortHolder {
  name: string;
  value: number;
  date: string;
}

// ─── static data ────────────────────────────────────────────────────────────
// Generated by yfinance daily close, last trading day of month, normalised to 100.
// Window: 2020-01 → 2026-05 (jan 2020 = 100, pre-pandemi baseline).
const COMPARISON_DATA: ComparisonPoint[] = [
  { date: "2020-01", ambu: 100.0, olympus: 100.0, bsx: 100.0, colo: 100.0, isrg: 100.0 },
  { date: "2020-02", ambu: 124.0, olympus: 109.9, bsx: 89.3, colo: 106.3, isrg: 95.4 },
  { date: "2020-03", ambu: 133.8, olympus: 87.5, bsx: 77.9, colo: 115.9, isrg: 88.5 },
  { date: "2020-04", ambu: 173.0, olympus: 96.7, bsx: 89.5, colo: 126.6, isrg: 91.3 },
  { date: "2020-05", ambu: 181.3, olympus: 104.9, bsx: 90.7, colo: 132.2, isrg: 103.6 },
  { date: "2020-06", ambu: 168.7, olympus: 116.3, bsx: 83.9, colo: 120.8, isrg: 101.8 },
  { date: "2020-07", ambu: 178.1, olympus: 105.5, bsx: 92.1, colo: 126.4, isrg: 122.4 },
  { date: "2020-08", ambu: 148.5, olympus: 117.6, bsx: 98.0, colo: 124.4, isrg: 130.6 },
  { date: "2020-09", ambu: 145.7, olympus: 122.3, bsx: 91.3, colo: 117.9, isrg: 126.8 },
  { date: "2020-10", ambu: 156.9, olympus: 111.5, bsx: 81.8, colo: 109.6, isrg: 119.2 },
  { date: "2020-11", ambu: 169.3, olympus: 126.4, bsx: 79.2, colo: 109.5, isrg: 129.7 },
  { date: "2020-12", ambu: 213.1, olympus: 126.4, bsx: 85.9, colo: 109.2, isrg: 146.1 },
  { date: "2021-01", ambu: 235.2, olympus: 105.9, bsx: 84.6, colo: 107.8, isrg: 133.6 },
  { date: "2021-02", ambu: 231.1, olympus: 125.0, bsx: 92.6, colo: 110.3, isrg: 131.6 },
  { date: "2021-03", ambu: 241.2, olympus: 128.4, bsx: 92.3, colo: 112.1, isrg: 132.0 },
  { date: "2021-04", ambu: 280.6, olympus: 125.9, bsx: 104.1, colo: 120.3, isrg: 154.5 },
  { date: "2021-05", ambu: 183.8, olympus: 131.7, bsx: 101.6, colo: 112.9, isrg: 150.4 },
  { date: "2021-06", ambu: 195.2, olympus: 123.7, bsx: 102.1, colo: 120.9, isrg: 164.3 },
  { date: "2021-07", ambu: 187.9, olympus: 125.8, bsx: 108.9, colo: 134.8, isrg: 177.1 },
  { date: "2021-08", ambu: 161.2, olympus: 129.5, bsx: 107.8, colo: 128.2, isrg: 188.2 },
  { date: "2021-09", ambu: 153.7, olympus: 137.7, bsx: 103.6, colo: 118.3, isrg: 177.6 },
  { date: "2021-10", ambu: 148.4, olympus: 137.9, bsx: 103.0, colo: 123.3, isrg: 193.5 },
  { date: "2021-11", ambu: 150.4, olympus: 142.3, bsx: 90.9, colo: 126.1, isrg: 173.8 },
  { date: "2021-12", ambu: 140.1, olympus: 148.5, bsx: 101.5, colo: 135.3, isrg: 192.6 },
  { date: "2022-01", ambu: 112.8, olympus: 142.7, bsx: 102.5, colo: 112.6, isrg: 152.3 },
  { date: "2022-02", ambu: 99.4, olympus: 128.9, bsx: 105.5, colo: 117.3, isrg: 155.6 },
  { date: "2022-03", ambu: 81.0, olympus: 131.1, bsx: 105.8, colo: 120.4, isrg: 161.7 },
  { date: "2022-04", ambu: 76.5, olympus: 129.4, bsx: 100.6, colo: 112.7, isrg: 128.2 },
  { date: "2022-05", ambu: 76.9, olympus: 150.8, bsx: 97.9, colo: 96.9, isrg: 122.0 },
  { date: "2022-06", ambu: 55.8, olympus: 152.8, bsx: 89.0, colo: 95.0, isrg: 107.6 },
  { date: "2022-07", ambu: 66.8, olympus: 157.9, bsx: 98.0, colo: 99.8, isrg: 123.4 },
  { date: "2022-08", ambu: 60.4, olympus: 168.7, bsx: 96.3, colo: 99.7, isrg: 110.3 },
  { date: "2022-09", ambu: 53.8, olympus: 155.7, bsx: 92.5, colo: 91.2, isrg: 100.5 },
  { date: "2022-10", ambu: 68.3, olympus: 176.0, bsx: 103.0, colo: 98.7, isrg: 132.1 },
  { date: "2022-11", ambu: 71.8, olympus: 157.2, bsx: 108.1, colo: 98.0, isrg: 144.9 },
  { date: "2022-12", ambu: 72.1, olympus: 131.8, bsx: 110.5, colo: 95.4, isrg: 142.2 },
  { date: "2023-01", ambu: 76.1, olympus: 136.1, bsx: 110.5, colo: 96.7, isrg: 131.7 },
  { date: "2023-02", ambu: 83.7, olympus: 128.6, bsx: 111.6, colo: 95.6, isrg: 122.9 },
  { date: "2023-03", ambu: 83.2, olympus: 129.9, bsx: 119.5, colo: 106.0, isrg: 136.9 },
  { date: "2023-04", ambu: 86.8, olympus: 132.7, bsx: 124.5, colo: 114.3, isrg: 161.4 },
  { date: "2023-05", ambu: 88.3, olympus: 118.7, bsx: 123.0, colo: 103.1, isrg: 165.0 },
  { date: "2023-06", ambu: 90.4, olympus: 127.0, bsx: 129.2, colo: 100.3, isrg: 183.3 },
  { date: "2023-07", ambu: 81.0, olympus: 129.8, bsx: 123.8, colo: 99.0, isrg: 173.9 },
  { date: "2023-08", ambu: 67.6, olympus: 110.4, bsx: 128.8, colo: 92.3, isrg: 167.6 },
  { date: "2023-09", ambu: 59.8, olympus: 108.8, bsx: 126.1, colo: 87.8, isrg: 156.6 },
  { date: "2023-10", ambu: 56.3, olympus: 112.0, bsx: 122.3, colo: 86.4, isrg: 140.5 },
  { date: "2023-11", ambu: 75.4, olympus: 121.4, bsx: 133.5, colo: 94.9, isrg: 166.6 },
  { date: "2023-12", ambu: 85.2, olympus: 114.3, bsx: 138.1, colo: 90.7, isrg: 180.8 },
  { date: "2024-01", ambu: 93.0, olympus: 123.3, bsx: 151.1, colo: 93.7, isrg: 202.7 },
  { date: "2024-02", ambu: 97.7, olympus: 119.5, bsx: 158.1, colo: 107.6, isrg: 206.7 },
  { date: "2024-03", ambu: 91.9, olympus: 124.2, bsx: 163.6, colo: 109.6, isrg: 213.9 },
  { date: "2024-04", ambu: 91.1, olympus: 123.3, bsx: 171.7, colo: 99.5, isrg: 198.6 },
  { date: "2024-05", ambu: 106.4, olympus: 138.6, bsx: 180.5, colo: 96.9, isrg: 215.5 },
  { date: "2024-06", ambu: 108.5, olympus: 145.3, bsx: 183.9, colo: 98.3, isrg: 238.4 },
  { date: "2024-07", ambu: 113.3, olympus: 145.9, bsx: 176.5, colo: 105.4, isrg: 238.3 },
  { date: "2024-08", ambu: 103.6, olympus: 149.0, bsx: 195.3, colo: 108.1, isrg: 264.0 },
  { date: "2024-09", ambu: 106.2, olympus: 152.3, bsx: 200.1, colo: 102.8, isrg: 263.3 },
  { date: "2024-10", ambu: 102.8, olympus: 151.9, bsx: 200.7, colo: 100.5, isrg: 270.0 },
  { date: "2024-11", ambu: 89.9, olympus: 132.2, bsx: 216.5, colo: 104.5, isrg: 290.5 },
  { date: "2024-12", ambu: 84.2, olympus: 132.8, bsx: 213.3, colo: 92.4, isrg: 279.7 },
  { date: "2025-01", ambu: 109.1, olympus: 132.6, bsx: 244.5, colo: 97.5, isrg: 306.5 },
  { date: "2025-02", ambu: 106.5, olympus: 114.7, bsx: 247.9, colo: 89.8, isrg: 307.2 },
  { date: "2025-03", ambu: 95.5, olympus: 109.1, bsx: 240.9, colo: 85.0, isrg: 265.4 },
  { date: "2025-04", ambu: 95.3, olympus: 104.5, bsx: 245.7, colo: 87.2, isrg: 276.4 },
  { date: "2025-05", ambu: 82.0, olympus: 104.0, bsx: 251.4, colo: 74.7, isrg: 296.0 },
  { date: "2025-06", ambu: 80.5, olympus: 96.1, bsx: 256.5, colo: 70.7, isrg: 291.2 },
  { date: "2025-07", ambu: 78.0, olympus: 101.5, bsx: 250.6, colo: 70.9, isrg: 257.8 },
  { date: "2025-08", ambu: 77.9, olympus: 96.5, bsx: 252.0, colo: 72.0, isrg: 253.7 },
  { date: "2025-09", ambu: 75.0, olympus: 104.8, bsx: 233.2, colo: 63.8, isrg: 239.7 },
  { date: "2025-10", ambu: 81.5, olympus: 106.4, bsx: 240.6, colo: 68.8, isrg: 286.3 },
  { date: "2025-11", ambu: 70.7, olympus: 117.7, bsx: 242.6, colo: 68.2, isrg: 307.3 },
  { date: "2025-12", ambu: 71.3, olympus: 111.2, bsx: 227.7, colo: 64.2, isrg: 303.5 },
  { date: "2026-01", ambu: 68.9, olympus: 103.2, bsx: 223.4, colo: 63.0, isrg: 270.2 },
  { date: "2026-02", ambu: 64.4, olympus: 85.6, bsx: 183.5, colo: 57.3, isrg: 269.8 },
  { date: "2026-03", ambu: 55.4, olympus: 83.4, bsx: 149.9, colo: 51.3, isrg: 247.1 },
  { date: "2026-04", ambu: 51.1, olympus: 86.7, bsx: 137.6, colo: 46.3, isrg: 245.2 },
  { date: "2026-05", ambu: 54.6, olympus: 100.1, bsx: 115.4, colo: 46.5, isrg: 227.6 },
];

// Operating margin per regnskabsår (Ambu's fiskaler slutter september)
// FY20/21 til FY23/24 fra yfinance Total Revenue / Operating Income.
// FY24/25 fra Ambu Interim Report Q4 2024/25 (5. november 2025): EBIT b.s.i. 13,0%.
const MARGIN_DATA: MarginPoint[] = [
  { fy: "FY20/21", margin: 8.5 },
  { fy: "FY21/22", margin: 2.7 },
  { fy: "FY22/23", margin: 6.3 },
  { fy: "FY23/24", margin: 12.0 },
  { fy: "FY24/25", margin: 13.0 },
];

// Aktuelle large short-positioner i Ambu (Zirium's egen database, 29. maj 2026)
const SHORT_HOLDERS: ShortHolder[] = [
  { name: "Wellington Management International Limited", value: 0.82, date: "14. maj 2026" },
  { name: "Millennium International Management LP",      value: 0.80, date: "27. maj 2026" },
  { name: "AHL Partners LLP",                            value: 0.70, date: "4. maj 2026" },
  { name: "J.P. Morgan Asset Management (UK) Limited",   value: 0.68, date: "6. nov 2025" },
  { name: "BlackRock Financial Management, Inc.",        value: 0.50, date: "1. maj 2026" },
  { name: "BlackRock Advisors, LLC",                     value: 0.50, date: "23. apr 2026" },
];

// ─── helpers ─────────────────────────────────────────────────────────────────
const formatDate = (ym: string): string => {
  const [y, m] = ym.split("-");
  const months = ["jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec"];
  return `${months[parseInt(m, 10) - 1]} ${y.slice(2)}`;
};

// ─── sub-components ──────────────────────────────────────────────────────────
function KPI({ value, label, highlight, tone = "blue" }: { value: string; label: string; highlight?: boolean; tone?: "blue" | "red" | "green" }) {
  const toneClasses = {
    blue:  { bg: "bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800",       text: "text-blue-600 dark:text-blue-400" },
    red:   { bg: "bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800",           text: "text-red-700 dark:text-red-400" },
    green: { bg: "bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800", text: "text-emerald-700 dark:text-emerald-400" },
  };
  const t = toneClasses[tone];
  return (
    <div className={`rounded-2xl border p-4 sm:p-5 text-center ${highlight ? t.bg : "bg-white dark:bg-[#19191f] border-gray-100 dark:border-gray-800"}`}>
      <p className={`text-lg sm:text-xl font-bold tabular-nums ${highlight ? t.text : "text-gray-900 dark:text-white"}`}>{value}</p>
      <p className="text-xs text-gray-500 dark:text-gray-300 mt-1 leading-tight">{label}</p>
    </div>
  );
}

function SectionHeader({ n, title }: { n: number; title: string }) {
  return (
    <h2 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-4">
      {n}. {title}
    </h2>
  );
}

// ─── main page ───────────────────────────────────────────────────────────────
const AmbuAnalysisPage: React.FC = () => {
  const navigate = useNavigate();

  useEffect(() => {
    trackPageView(`/analyse/${SLUG}`, "Ambu analyse");
    fetch(`${HOST}/stats/visit/ambu-analysis/`).catch(() => {});
  }, []);

  return (
    <PageTemplate>
      <title>Ambu: Fald trods en succesfuld transformation | Zirium</title>
      <meta
        name="description"
        content="Ambu ligger 45% under sit pre-pandemi-niveau, selvom selskabet operationelt har gennemført en stærk transformation under CEO Britt Meelby Jensen med margin der er næsten femdoblet. Men aktien bliver ved at falde. Vi ser på paradokset, tariff-presset og hedgefondenes historisk høje shortinteresse."
      />
      <meta property="og:title" content="Ambu: Fald trods en succesfuld transformation" />
      <meta property="og:description" content="Ambu ligger 45% under pre-pandemi-niveauet trods næsten femdoblet margin. Hedgefonde har historisk høj shortinteresse. Hvad er paradokset?" />
      <meta property="og:type" content="article" />
      <meta property="og:url" content={`https://www.zirium.dk/analyse/${SLUG}`} />
      <meta property="og:image" content="https://www.zirium.dk/og-images/ambu-2026-06-01.png" />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:type" content="image/png" />
      <meta property="og:site_name" content="Zirium" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Ambu: Fald trods en succesfuld transformation" />
      <meta name="twitter:description" content="Ambu ligger 45% under pre-pandemi-niveauet trods næsten femdoblet margin. Hedgefonde har historisk høj shortinteresse." />
      <meta name="twitter:image" content="https://www.zirium.dk/og-images/ambu-2026-06-01.png" />
      <script type="application/ld+json">{JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "Ambu: Fald trods en succesfuld transformation",
        "description": "Ambu ligger 45% under sit pre-pandemi-niveau fra 2020. Operationelt har selskabet gennemført en stærk transformation, men aktien fortsætter ned.",
        "author": { "@type": "Person", "name": "Araz Bayat Makoo" },
        "publisher": { "@type": "Organization", "name": "Zirium", "url": "https://www.zirium.dk" },
        "datePublished": "2026-06-01",
        "mainEntityOfPage": `https://www.zirium.dk/analyse/${SLUG}`,
        "inLanguage": "da",
      })}</script>

      <article className="w-full max-w-[900px] mx-auto px-5 sm:px-8 pb-10 sm:pb-16">
        <button
          className="text-blue-600 hover:text-blue-700 bg-transparent border-none text-base inline-flex items-center gap-1.5 focus:ring-2 focus:ring-blue-300 rounded-sm min-h-[44px] min-w-[44px]"
          onClick={() => {
            if (window.history.length > 1 && window.history.state?.idx > 0) {
              navigate(-1);
            } else {
              navigate("/analyse");
            }
          }}
        >
          <span aria-hidden="true">←</span>
          Tilbage
        </button>

        {/* Header */}
        <header className="mb-10 mt-4">
          <p className="text-base text-gray-600 dark:text-gray-300 mb-4">
            Analyse lavet af Araz Bayat Makoo (Zirium) - 1. juni 2026
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-gray-900 dark:text-white mb-3 leading-tight">
            Ambu: Fald trods en succesfuld transformation
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 leading-relaxed">
            Ambu A/S (AMBU-B)
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Ambu handler i dag omkring 67,40 DKK, cirka 45% under niveauet
            fra januar 2020, altså før pandemien overhovedet begyndte.
            Undervejs næsten tredoblede aktien sig til en pandemi-top på
            355,40 DKK den 27. april 2021, før den kollapsede. Den faldt
            helt til 61,70 DKK den 29. april 2026, det laveste niveau siden
            efteråret 2022, og ligger nu cirka 81% under toppen.
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            En stor del af faldet skyldes ikke svag drift, men en korrektion
            af en ekstrem værdiansættelse. På det højeste handlede aktien til
            en P/E langt over 100 på rullende indtjening. Så høje multipler
            har historisk sjældent været holdbare uden ekstrem og vedvarende
            vækst, og da både vækst og marginer samtidig normaliserede, fulgte
            et hårdt tilbagefald.
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Det paradoksale er, at selskabet driftsmæssigt har gennemført en
            af de stærkeste transformationer i dansk sundhedssektor under
            adm. direktør Britt Meelby Jensen. Driftsmarginen før særlige
            poster er næsten femdoblet fra 2,7% i regnskabsåret 2021/22 til
            13,0% i 2024/25, den organiske omsætningsvækst landede på 13,1% i
            seneste regnskabsår, og selskabet har nu flere kontanter end
            gæld. Alligevel bliver aktien ved at falde. Hvorfor?
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Vi gennemgår kursudviklingen siden 2020 sammenlignet med
            konkurrenterne, transformationen under ZOOM IN-strategien, den nye
            ZOOM AHEAD-plan mod FY29/30, det aktuelle tariff-pres og
            hedgefondenes historisk høje shortinteresse i selskabet.
          </p>
        </header>

        {/* KPIs */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-12">
          <KPI value="-45%" label="Afkast siden jan 2020" highlight tone="red" />
          <KPI value="+188%" label="Til pandemi-toppen (apr 2021)" />
          <KPI value="-81%" label="Fra rekordniveau" />
          <KPI value="6,96%" label="Short interest (29/5)" highlight tone="red" />
        </div>

        {/* Section 1 */}
        <section className="mb-12">
          <SectionHeader n={1} title="Hvor stort er problemet egentlig?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Sammenligningen siden januar 2020, altså før pandemien, fortæller
            to ting. For det første er det ikke en bred sektorkrise: Intuitive
            Surgical er mere end fordoblet (+128%), Boston Scientific er steget
            15%, og selv japanske Olympus (den klare genbrugs-konkurrent) er
            omtrent tilbage på sit start-niveau (cirka 0%). For det andet er Ambus
            kursrejse unik: Aktien næsten tredoblede sig til pandemi-toppen og
            er nu faldet helt tilbage til cirka 45% under udgangspunktet. Kun
            Coloplast (-53%) har et lignende samlet fald, men uden Ambus
            ekstreme spike op og ned.
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Graf: Sammenligning af Ambu vs Olympus, Boston Scientific, Coloplast og Intuitive Surgical siden januar 2020">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Ambu vs. 4 medical device-peers (jan 2020 = 100)</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Månedsslut, prisindeks (uden udbytter), lokal valuta</p>
            <ResponsiveContainer width="100%" height={320}>
              <LineChart data={COMPARISON_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis
                  dataKey="date"
                  tick={{ fontSize: 11, fill: "#6b7280" }}
                  tickFormatter={formatDate}
                  interval={11}
                />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} domain={[40, 320]} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => Number(v).toFixed(1)}
                  labelFormatter={(label) => formatDate(String(label))}
                />
                <Legend wrapperStyle={{ fontSize: 12 }} />
                <ReferenceLine y={100} stroke="#9ca3af" strokeDasharray="3 3" />
                <Line type="monotone" dataKey="isrg" name="Intuitive Surgical" stroke="#10b981" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="bsx" name="Boston Scientific" stroke="#3b82f6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="olympus" name="Olympus" stroke="#f59e0b" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="colo" name="Coloplast" stroke="#8b5cf6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="ambu" name="Ambu" stroke="#ef4444" strokeWidth={3} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>

          <p className="text-xs text-gray-500 dark:text-gray-400 italic leading-relaxed">
            Note: Sammenligningen bruger prisindekser uden reinvesterede
            udbytter for at sikre sammenlignelighed, normaliseret til 100 i
            januar 2020. Afkast er målt i lokal valuta og er ikke
            valuta-justeret. For Olympus (noteret i JPY) ville en
            valuta-justering til DKK trække det viste niveau (omtrent 0%) ned
            i negativt territorium, da yen er svækket markant over for kronen
            i perioden.
          </p>
        </section>

        {/* Section 2 */}
        <section className="mb-12">
          <SectionHeader n={2} title="Pandemi-eufori, boble-værdiansættelse og kollaps" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Ambus toppris på 355,40 DKK den 27. april 2021 var et resultat
            af en perfekt storm under COVID-19. Engangsendoskoper, som var
            Ambus kerneprodukt, blev pludselig set som en smitterisiko-løsning,
            fordi genbrugsinstrumenter krævede genbrugsprocessering der
            blev anset som en risikofaktor under pandemien. Hospitalerne
            købte massivt og opbyggede lagre langt over normal forbrugsrate.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Den kombinerede effekt var dramatisk på både regnskaber og
            værdiansættelse. Aktien næsten tredoblede sig fra januar 2020 til
            april 2021, og markedet priste Ambu som om engangsendoskoper-paradigmet
            var ved at overtage hele endoskopi-markedet på få år. På det
            højeste handlede aktien til en P/E langt over 100 på rullende
            indtjening, et niveau der historisk kun ses på rene
            fortælling-aktier i ekstreme boble-toppe.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Det betyder, at en stor del af Ambus efterfølgende fald var en
            værdiansættelses-reset snarere end ren operationel kritik. Selv
            hvis indtjeningen havde holdt sig konstant, ville et fald i
            multiplen fra over 100x til omkring 25x i sig selv have skåret
            aktien ned til en fjerdedel. Men faldet handlede ikke kun om
            multiplen: 2021-2022 var især en værdiansættelses-reset, mens
            2022-2024 også var præget af reel fundamental skuffelse.
            Indtjeningen kollapsede (EBIT-margin fra 8,5% til 2,7% på et
            regnskabsår), væksten bremsede da hospitalernes pandemilagre
            normaliserede, og single-use-udbredelsen i GI gik langsommere
            end håbet.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Til den interne corporate governance-historik hører også Lars
            Marcher-sagen fra 10. maj 2019, hvor den fyrede CEO sad med 3,8 mio.
            aktier privat og nægtede at oplyse om han solgte efter fyringen,
            hvor offentliggørelseskravet ikke længere gjaldt. Dansk
            Aktionærforening kritiserede dette som et regelhul. Episoden er
            ikke direkte årsag til faldet siden 2021, men den prægede en
            periode hvor mange institutionelle investorer blev forsigtige med
            Ambu som ledelses-case. Det var Juan José González der overtog som
            CEO efter Marcher og ledte Ambu gennem hele boom-og-bust-perioden,
            indtil bestyrelsen i maj 2022 hentede Britt Meelby Jensen ind for
            at lede genopretningen.
          </p>
        </section>

        {/* Section 3 */}
        <section className="mb-12">
          <SectionHeader n={3} title="ZOOM IN: Britt Meelby Jensens omstilling" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Britt Meelby Jensen tiltrådte som CEO den 20. maj 2022. Hun kom
            med en sjælden kombination af baggrunde: CEO for Atos Medical
            (medical device) frem til at hun solgte selskabet til Coloplast
            i begyndelsen af 2022, og før det CEO for Zealand Pharma fra 2015
            til 2019. Hun forstår både medical device-kommerciel ekspansion
            og pharma-pipeline-eksekvering.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            I november 2022 lancerede hun ZOOM IN-strategien med tre klare
            målsætninger: Genskab finansielle fundamenter, gennemfør strategisk
            fokusering, og afvikl gæld. Strategien blev eksekveret over tre
            år frem mod 2025. Tabellen viser margin-progressionen klart:
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Graf: Ambu's operating margin progression FY21 til FY24">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Ambu operating margin per regnskabsår</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Margin (%) per fiskalt år (slutter 30. september). Kilde: Ambu annual reports.</p>
            <ResponsiveContainer width="100%" height={260}>
              <BarChart data={MARGIN_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis dataKey="fy" tick={{ fontSize: 11, fill: "#6b7280" }} />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} tickFormatter={(v) => `${v}%`} domain={[0, 18]} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => `${Number(v).toFixed(1).replace(".", ",")}%`}
                />
                <Bar dataKey="margin" name="EBIT margin" fill="#2563eb" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Marginen er næsten femdoblet fra 2,7% til 13,0% over fire
            regnskabsår. I FY24/25 (afsluttet 30. september 2025) leverede
            Ambu organisk omsætningsvækst på 13,1%, free cash flow før opkøb
            på 407 mio. DKK, og selskabet endte med netto-kontant-position
            på 319 mio. DKK. Bestyrelsen har samtidig vedtaget at returnere
            260 mio. DKK til aktionærerne via udbytte (110 mio. DKK) og
            aktietilbagekøb (150 mio. DKK). Operationelt er transformationen
            reel og bekræftet i de officielle tal.
          </p>
        </section>

        {/* Section 4 */}
        <section className="mb-12">
          <SectionHeader n={4} title="ZOOM AHEAD: nye ambitioner mod FY29/30" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            I september 2025 annoncerede Ambu opfølgningsstrategien ZOOM
            AHEAD, der hæver de langsigtede mål. For FY29/30 har Ambu nu
            følgende officielle mål:
          </p>
          <ul className="space-y-2 text-gray-600 dark:text-gray-300 leading-relaxed list-disc pl-6 mb-4">
            <li><strong>Organisk omsætningsvækst 11-13% CAGR</strong> (op fra +10% mod FY27/28)</li>
            <li><strong>Endoscopy Solutions: 15-20% CAGR</strong> som vækst-motor</li>
            <li><strong>Anaesthesia &amp; Patient Monitoring: 3-5% CAGR</strong> som stabil base</li>
            <li><strong>EBIT-margin på +20%</strong> (samme niveau som tidligere FY27/28-mål)</li>
            <li><strong>Cash conversion på +40%</strong> (FCF før opkøb / EBITDA)</li>
          </ul>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Endoscopy Solutions er omdrejningspunktet og indeholder
            kerneproduktlinjen aScope. Senest har Ambu lanceret aScope 5
            Broncho (top-tier bronkoskop), aScope Gastro Large (4,2 mm
            arbejdskanal til avancerede GI-procedurer) og er ved at udvikle
            en koloskopilinje. Strategien handler om at udbrede
            engangs-modellen til markeder, hvor Olympus' genbrugsinstrumenter
            stadig dominerer.
          </p>
        </section>

        {/* Section 5 */}
        <section className="mb-12">
          <SectionHeader n={5} title="Tariff-pres og en svagere Q2" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Den 5. november 2025 rapporterede Ambu deres FY24/25-regnskab,
            og aktien faldt cirka 16% på dagen. Årsagen var ikke svag drift,
            men en kombination af tariff-omkostninger og valutamodvind. Q4
            FY24/25 (kvartalet juli til september 2025) leverede en
            EBIT-margin før særlige poster på 10,0% mod konsensus omkring
            12-13%. Tariff-effekten og en svækket USD over for DKK var
            hovedansvarlige.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Trump-administrationens tariffer på medicinske produkter
            produceret uden for USA ramte Ambu særligt hårdt, fordi Ambus
            primære produktionscentre ligger i Malaysia og Mexico. Selskabet
            har annonceret en plan om at flytte hele den nordamerikanske
            endoskopi-efterspørgsel til lokal produktion inden FY29/30, men
            indtil da må Ambu absorbere omkostningerne.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Ved årsregnskabet guidede Ambu FY25/26 til organisk
            omsætningsvækst på 10-13% og EBIT-margin før særlige poster på
            12-14% (14-16% eksklusive tariff-impacten på cirka 2
            procentpoint). Det er den primære grund til at marginerne falder
            kortvarigt efter at have toppet på 16,1% i Q1 FY24/25 (kvartalet
            oktober-december 2024).
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Den 6. maj 2026 bekræftede Q2-regnskabet for 2025/26 markedets
            bekymring. Den organiske vækst bremsede til 7,3% i kvartalet mod
            13,1% i hele FY24/25. Endoscopy Solutions voksede fortsat stærkt
            (+13,8%), men Anesthesia & Patient Monitoring faldt 2,5%, og
            EBIT-marginen lå på 11,0% i kvartalet. Samtidig sænkede Ambu sin
            helårsguidance for organisk vækst til 10-12% (fra 10-13%). For et
            marked der allerede tvivlede på eksekveringen, var en
            vækstopbremsning kombineret med en nedjustering præcis det
            forkerte signal.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Som modtræk lancerede bestyrelsen samtidig et aktietilbagekøb på
            op til 300 mio. DKK, der løber fra 6. maj til senest 30. september
            2026. Det signalerer, at ledelsen selv vurderer aktien som
            undervurderet, og kan lægge en vis støtte under kursen på kort
            sigt.
          </p>
        </section>

        {/* Section 6 */}
        <section className="mb-12">
          <SectionHeader n={6} title="Hedgefondenes historisk høje shortinteresse" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Den 29. maj 2026 stod den samlede shortinteresse i Ambu på 6,96%
            af aktiekapitalen. Toppen på 7,38% blev nået den 7. maj 2026,
            kun tre uger før denne analyse. Det er det højeste niveau Ambu
            har haft i Finanstilsynets registreringer, og det indikerer
            betydelig skepsis blandt dele af den professionelle investorbase
            over for ZOOM AHEAD-targetene. Høj shortinteresse kan dog også
            afspejle factor-, pair- eller market-neutral-strategier og ikke
            kun ren fundamental skepsis.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            De største offentligt registrerede short-positioner kommer fra
            en blanding af multi-strategy hedgefonde og store kapitalforvaltere:
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-4 sm:p-5 mb-4 overflow-x-auto">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-3">
              Største offentligt registrerede short-positioner i Ambu
            </h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs uppercase tracking-wide text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">
                  <th className="pb-2 pr-3">Holder</th>
                  <th className="pb-2 text-right">Position</th>
                  <th className="pb-2 pl-3 text-right">Senest ændret</th>
                </tr>
              </thead>
              <tbody className="text-gray-700 dark:text-gray-300">
                {SHORT_HOLDERS.map((h) => (
                  <tr key={h.name} className="border-b border-gray-100 dark:border-gray-800">
                    <td className="py-2 pr-3">{h.name}</td>
                    <td className="py-2 text-right tabular-nums font-semibold text-red-600 dark:text-red-400">{h.value.toString().replace(".", ",")}%</td>
                    <td className="py-2 pl-3 text-right text-xs text-gray-500 dark:text-gray-400">{h.date}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-3 leading-relaxed">
              Kilde: Finanstilsynets register over store korte positioner via
              Zirium. Kun positioner over 0,5% offentliggøres.
            </p>
          </div>

          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Det er værd at notere, at både Millennium og AHL er klassiske
            multi-strategy hedgefonde, mens Wellington og BlackRock primært
            er store kapitalforvaltere, hvis short-positioner typisk kommer
            fra deres hedgefond- eller alternative produkter snarere end
            deres traditionelle long-only-fonde. Sammensætningen viser at
            skepsissen kommer både fra kortsigtede traders og fra langsigtede
            forvaltere.
          </p>
        </section>

        {/* Section 7 */}
        <section className="mb-12">
          <SectionHeader n={7} title="Hvorfor bliver aktien ved at falde?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Paradokset er klart: Operationelt er Ambu på sporet, men aktien
            har fortsat ned. Der er fem forklaringer der spiller sammen:
          </p>
          <ol className="space-y-3 text-gray-600 dark:text-gray-300 leading-relaxed list-decimal pl-6 mb-4">
            <li>
              <strong>Den seneste vækst skuffede.</strong>{" "}
              Q2-regnskabet i maj 2026 viste en opbremsning til 7,3% organisk
              vækst og en nedjustering af helårsguidancen til 10-12%. Når
              multiplen stadig er høj, straffer markedet enhver svaghed i
              væksten ekstra hårdt.
            </li>
            <li>
              <strong>Tariff- og FX-modvind tager toppen af margin-løftet.</strong>{" "}
              FY25/26-vejledningen er 12-14% EBIT-margin mod tidligere håb
              om 14-16%. Det er ikke en stor forskel, men det får analytikere
              til at justere terminalværdier ned, og de værdiorienterede investorer
              tøver med at træde ind før der er klarhed.
            </li>
            <li>
              <strong>Single-use konverteringsraten er langsommere end forventet.</strong>{" "}
              Olympus' genbrugsendoskoper er dybt integrerede i hospitalernes
              arbejdsgange, og overgangen til engangsudstyr kræver
              investering i skærme (aBox/aView) samt klinisk oplæring. Selv
              med veldokumenterede smitte- og produktivitetsfordele tager
              udbredelsen tid.
            </li>
            <li>
              <strong>Værdiansættelsen er stadig høj.</strong>{" "}
              Selv efter kursfaldet handler Ambu til cirka 22x forward P/E og
              cirka 3x indre værdi. For en margin-historie, hvor markedet er
              usikker på holdbarheden i en tariff-præget verden, er det endnu
              ikke billigt nok for de værdiorienterede investorer.
            </li>
            <li>
              <strong>Hedgefondene har historisk høj shortinteresse.</strong>{" "}
              6,96% short interest med store navne som Wellington og
              Millennium betyder, at den marginale køber stadig møder en
              marginal sælger der vil shorte mere ved enhver kursstigning.
            </li>
          </ol>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Markedet straffer ikke transformationen. Det signalerer i stedet
            usikkerhed om holdbarheden af margin-løftet i en tariff-præget
            verden, og det venter på bevis for at engangs-endoskopi reelt
            bliver standarden i antallet af procedurer, ikke kun i Ambus
            produktlinje.
          </p>
        </section>

        {/* Section 8 */}
        <section className="mb-12">
          <SectionHeader n={8} title="Konklusion" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            Ambu er den interessante kontradiktion på dansk børs: Et selskab
            der operationelt har gjort næsten alt rigtigt under ny ledelse,
            men hvor aktien fortsætter med at falde. EBIT-marginen er næsten
            femdoblet (fra 2,7% til 13,0%), gælden er afviklet, og strategien
            er klar med ambitiøse FY29/30-mål.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            Modsiden er, at markedet pt. priser tariff-presset, langsom
            udbredelse af engangsudstyr og en rig værdiansættelse hårdere
            end den opnåede transformation. Hedgefondenes shortinteresse på et
            historisk topniveau er det tydeligste signal om at den
            professionelle investorbase ikke tror på et hurtigt comeback.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            For investorer er Ambu en case om timing. Den fundamentale
            historie er ikke gået i stykker, men aktiekursen reflekterer en
            verden hvor tariffer, valuta og konkurrence-friktion tager
            længere tid at arbejde sig igennem end markedet havde håbet.
            Hvis Ambu både leverer margin- og vækstmålene i ZOOM AHEAD mod
            FY29/30, kan dagens kurs vise sig attraktiv i bakspejlet. Hvis
            tarifferne
            normaliseres langsommere, eller udbredelsen af engangsudstyr
            skuffer, kan aktien fortsætte ned. Det igangværende tilbagekøb på
            300 mio. DKK kan lægge en kortsigtet bund, men afgør ikke
            vækstspørgsmålet. Det er den balance investorer må veje.
          </p>
        </section>

        {/* Feedback widget */}
        <FeedbackWidget pageType="analysis" pageId={SLUG} />

        {/* Related */}
        <RelatedAnalyses currentSlug={SLUG} />

        {/* Disclaimer */}
        <footer className="border-t border-gray-100 dark:border-gray-800 pt-6">
          <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed text-center">
            <strong>Kilder:</strong> Yahoo Finance via yfinance (aktie- og
            indeks-afkast), Ambu annual reports og pressemeddelelser
            (operating margin, ZOOM IN/AHEAD-strategi), Finanstilsynets
            register over store korte positioner via Zirium.{" "}
            <strong>Ansvarsfraskrivelse:</strong>{" "}
            Denne analyse er alene til informationsformål og udgør ikke
            investeringsrådgivning. Historisk afkast er ikke en garanti for
            fremtidigt afkast. Foretag altid din egen analyse, og søg
            professionel rådgivning før du handler.
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-400 text-center mt-3">
            Copyright Zirium  |  1. juni 2026
          </p>
        </footer>
      </article>
    </PageTemplate>
  );
};

export default AmbuAnalysisPage;
