import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import PageTemplate from "../components/PageTemplate";
import RelatedAnalyses from "../components/RelatedAnalyses";
import FeedbackWidget from "../components/FeedbackWidget";
import { trackPageView } from "../analytics";
import { HOST } from "../apis/ShortPositionAPI";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine,
} from "recharts";

const SLUG = "c25/2026-05-28";

// ─── types ───────────────────────────────────────────────────────────────────
interface ComparisonPoint {
  date: string;
  c25: number;
  sp500: number;
  nasdaq: number;
  stoxx: number;
  omx: number;
}

interface SectorPoint {
  sector: string;
  y2020: number;
  y2021: number;
  y2026: number;
}

// ─── static data ────────────────────────────────────────────────────────────
// Generated by scripts/c25_chart_data.py
// Source: Yahoo Finance daily close, last trading day of month, normalised to 100.
// Data window: 2021-05-31 → 2026-05-31 (61 points)
const COMPARISON_DATA: ComparisonPoint[] = [
  { date: "2021-05", c25: 100.0, sp500: 100.0, nasdaq: 100.0, stoxx: 100.0, omx: 100.0 },
  { date: "2021-06", c25: 103.0, sp500: 102.2, nasdaq: 105.5, stoxx: 101.4, omx: 100.9 },
  { date: "2021-07", c25: 106.6, sp500: 104.5, nasdaq: 106.7, stoxx: 103.4, omx: 105.7 },
  { date: "2021-08", c25: 109.4, sp500: 107.6, nasdaq: 111.0, stoxx: 105.4, omx: 104.9 },
  { date: "2021-09", c25: 104.1, sp500: 102.5, nasdaq: 105.1, stoxx: 101.8, omx: 100.8 },
  { date: "2021-10", c25: 109.2, sp500: 109.5, nasdaq: 112.7, stoxx: 106.4, omx: 102.2 },
  { date: "2021-11", c25: 104.2, sp500: 108.6, nasdaq: 113.0, stoxx: 103.6, omx: 100.0 },
  { date: "2021-12", c25: 108.8, sp500: 113.4, nasdaq: 113.8, stoxx: 109.4, omx: 107.9 },
  { date: "2022-01", c25: 98.4, sp500: 107.4, nasdaq: 103.6, stoxx: 105.0, omx: 102.2 },
  { date: "2022-02", c25: 97.7, sp500: 104.0, nasdaq: 100.0, stoxx: 101.4, omx: 95.2 },
  { date: "2022-03", c25: 98.9, sp500: 107.8, nasdaq: 103.4, stoxx: 102.0, omx: 93.5 },
  { date: "2022-04", c25: 97.7, sp500: 98.3, nasdaq: 89.7, stoxx: 100.8, omx: 91.8 },
  { date: "2022-05", c25: 93.2, sp500: 98.3, nasdaq: 87.9, stoxx: 99.2, omx: 91.1 },
  { date: "2022-06", c25: 87.2, sp500: 90.0, nasdaq: 80.2, stoxx: 91.1, omx: 83.5 },
  { date: "2022-07", c25: 98.0, sp500: 98.2, nasdaq: 90.1, stoxx: 98.1, omx: 90.7 },
  { date: "2022-08", c25: 91.5, sp500: 94.1, nasdaq: 85.9, stoxx: 92.9, omx: 85.7 },
  { date: "2022-09", c25: 79.7, sp500: 85.3, nasdaq: 76.9, stoxx: 86.8, omx: 81.6 },
  { date: "2022-10", c25: 87.2, sp500: 92.1, nasdaq: 79.9, stoxx: 92.3, omx: 87.8 },
  { date: "2022-11", c25: 93.4, sp500: 97.1, nasdaq: 83.4, stoxx: 98.5, omx: 93.8 },
  { date: "2022-12", c25: 94.2, sp500: 91.3, nasdaq: 76.1, stoxx: 95.1, omx: 91.1 },
  { date: "2023-01", c25: 94.0, sp500: 97.0, nasdaq: 84.3, stoxx: 101.4, omx: 98.1 },
  { date: "2023-02", c25: 98.6, sp500: 94.4, nasdaq: 83.3, stoxx: 103.2, omx: 99.3 },
  { date: "2023-03", c25: 99.1, sp500: 97.7, nasdaq: 88.9, stoxx: 102.5, omx: 99.2 },
  { date: "2023-04", c25: 100.7, sp500: 99.2, nasdaq: 88.9, stoxx: 104.4, omx: 101.3 },
  { date: "2023-05", c25: 99.8, sp500: 99.4, nasdaq: 94.1, stoxx: 101.1, omx: 99.7 },
  { date: "2023-06", c25: 100.6, sp500: 105.9, nasdaq: 100.3, stoxx: 103.4, omx: 103.0 },
  { date: "2023-07", c25: 100.2, sp500: 109.2, nasdaq: 104.3, stoxx: 105.5, omx: 100.4 },
  { date: "2023-08", c25: 96.2, sp500: 107.2, nasdaq: 102.1, stoxx: 102.6, omx: 97.5 },
  { date: "2023-09", c25: 94.2, sp500: 102.0, nasdaq: 96.1, stoxx: 100.8, omx: 96.1 },
  { date: "2023-10", c25: 89.7, sp500: 99.8, nasdaq: 93.5, stoxx: 97.1, omx: 92.6 },
  { date: "2023-11", c25: 95.7, sp500: 108.7, nasdaq: 103.5, stoxx: 103.3, omx: 99.6 },
  { date: "2023-12", c25: 100.8, sp500: 113.5, nasdaq: 109.2, stoxx: 107.2, omx: 107.0 },
  { date: "2024-01", c25: 102.8, sp500: 115.3, nasdaq: 110.3, stoxx: 108.7, omx: 105.1 },
  { date: "2024-02", c25: 105.0, sp500: 121.2, nasdaq: 117.0, stoxx: 110.7, omx: 109.4 },
  { date: "2024-03", c25: 107.6, sp500: 125.0, nasdaq: 119.1, stoxx: 114.8, omx: 112.3 },
  { date: "2024-04", c25: 105.5, sp500: 119.8, nasdaq: 113.9, stoxx: 113.0, omx: 114.0 },
  { date: "2024-05", c25: 109.8, sp500: 125.5, nasdaq: 121.7, stoxx: 116.0, omx: 116.2 },
  { date: "2024-06", c25: 108.2, sp500: 129.9, nasdaq: 129.0, stoxx: 114.5, omx: 114.6 },
  { date: "2024-07", c25: 111.3, sp500: 131.4, nasdaq: 128.0, stoxx: 116.0, omx: 116.4 },
  { date: "2024-08", c25: 110.2, sp500: 134.4, nasdaq: 128.8, stoxx: 117.5, omx: 115.8 },
  { date: "2024-09", c25: 108.0, sp500: 137.1, nasdaq: 132.3, stoxx: 117.0, omx: 117.2 },
  { date: "2024-10", c25: 103.9, sp500: 135.7, nasdaq: 131.6, stoxx: 113.1, omx: 113.4 },
  { date: "2024-11", c25: 102.6, sp500: 143.5, nasdaq: 139.8, stoxx: 114.2, omx: 112.1 },
  { date: "2024-12", c25: 98.4, sp500: 139.9, nasdaq: 140.5, stoxx: 113.0, omx: 110.8 },
  { date: "2025-01", c25: 98.2, sp500: 143.7, nasdaq: 142.8, stoxx: 120.8, omx: 119.1 },
  { date: "2025-02", c25: 102.5, sp500: 141.6, nasdaq: 137.1, stoxx: 124.7, omx: 121.5 },
  { date: "2025-03", c25: 92.3, sp500: 133.5, nasdaq: 125.8, stoxx: 119.5, omx: 111.2 },
  { date: "2025-04", c25: 91.7, sp500: 132.5, nasdaq: 126.9, stoxx: 118.1, omx: 108.6 },
  { date: "2025-05", c25: 97.5, sp500: 140.6, nasdaq: 139.0, stoxx: 122.8, omx: 111.3 },
  { date: "2025-06", c25: 94.5, sp500: 147.6, nasdaq: 148.2, stoxx: 121.2, omx: 111.2 },
  { date: "2025-07", c25: 92.2, sp500: 150.8, nasdaq: 153.6, stoxx: 122.2, omx: 115.1 },
  { date: "2025-08", c25: 92.3, sp500: 153.7, nasdaq: 156.1, stoxx: 123.1, omx: 117.1 },
  { date: "2025-09", c25: 90.2, sp500: 159.1, nasdaq: 164.8, stoxx: 124.9, omx: 118.8 },
  { date: "2025-10", c25: 93.3, sp500: 162.7, nasdaq: 172.6, stoxx: 128.0, omx: 123.4 },
  { date: "2025-11", c25: 96.7, sp500: 162.9, nasdaq: 169.9, stoxx: 129.0, omx: 124.4 },
  { date: "2025-12", c25: 101.0, sp500: 162.8, nasdaq: 169.0, stoxx: 132.7, omx: 128.6 },
  { date: "2026-01", c25: 105.5, sp500: 165.1, nasdaq: 170.6, stoxx: 136.8, omx: 135.0 },
  { date: "2026-02", c25: 95.9, sp500: 163.6, nasdaq: 164.9, stoxx: 141.9, omx: 143.8 },
  { date: "2026-03", c25: 93.1, sp500: 155.3, nasdaq: 157.0, stoxx: 130.5, omx: 130.7 },
  { date: "2026-04", c25: 96.4, sp500: 171.5, nasdaq: 181.1, stoxx: 136.8, omx: 136.5 },
  { date: "2026-05", c25: 98.4, sp500: 178.9, nasdaq: 194.0, stoxx: 140.6, omx: 140.8 },
];

// Sector weights from official Nasdaq Index factsheets.
// Consolidated into 7 comparable categories (Nasdaq reclassified between 2020 and 2021).
// 2020 "Oil & Gas" = Energy (only Vestas). 2020 "Consumer Goods" = Consumer Staples + Consumer Discretionary combined.
const SECTOR_TIMELINE_DATA: SectorPoint[] = [
  { sector: "Healthcare",  y2020: 47.15, y2021: 41.59, y2026: 33.19 },
  { sector: "Industrials", y2020: 19.29, y2021: 25.30, y2026: 27.79 },
  { sector: "Financials",  y2020: 5.27,  y2021: 6.81,  y2026: 16.86 },
  { sector: "Energy",      y2020: 11.33, y2021: 8.51,  y2026: 10.79 },
  { sector: "Consumer",    y2020: 9.00,  y2021: 9.54,  y2026: 7.16 },
  { sector: "Utilities",   y2020: 6.37,  y2021: 7.01,  y2026: 4.21 },
  { sector: "Technology",  y2020: 1.61,  y2021: 1.25,  y2026: 0.00 },
];

// ─── helpers ─────────────────────────────────────────────────────────────────
const formatDate = (ym: string): string => {
  const [y, m] = ym.split("-");
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return `${months[parseInt(m, 10) - 1]} ${y.slice(2)}`;
};

// ─── sub-components ──────────────────────────────────────────────────────────
function KPI({ value, label, highlight, tone = "blue" }: { value: string; label: string; highlight?: boolean; tone?: "blue" | "red" | "green" }) {
  const toneClasses = {
    blue:  { bg: "bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800",       text: "text-blue-600 dark:text-blue-400" },
    red:   { bg: "bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800",           text: "text-red-700 dark:text-red-400" },
    green: { bg: "bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800", text: "text-emerald-700 dark:text-emerald-400" },
  };
  const t = toneClasses[tone];
  return (
    <div className={`rounded-2xl border p-4 sm:p-5 text-center ${highlight ? t.bg : "bg-white dark:bg-[#19191f] border-gray-100 dark:border-gray-800"}`}>
      <p className={`text-lg sm:text-xl font-bold tabular-nums ${highlight ? t.text : "text-gray-900 dark:text-white"}`}>{value}</p>
      <p className="text-xs text-gray-500 dark:text-gray-300 mt-1 leading-tight">{label}</p>
    </div>
  );
}

function SectionHeader({ n, title }: { n: number; title: string }) {
  return (
    <h2 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-4">
      {n}. {title}
    </h2>
  );
}

function StockBlock({ name, returnLabel, children }: { name: string; returnLabel: string; children: React.ReactNode }) {
  const isPositive = returnLabel.trim().startsWith("+");
  return (
    <div className="mb-6">
      <div className="flex flex-wrap items-baseline justify-between gap-2 mb-2 pb-2 border-b border-gray-100 dark:border-gray-800">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white">{name}</h3>
        <span className={`text-base font-bold tabular-nums ${isPositive ? "text-emerald-700 dark:text-emerald-400" : "text-red-600 dark:text-red-400"}`}>
          {returnLabel}
        </span>
      </div>
      <p className="text-gray-600 dark:text-gray-300 leading-relaxed">{children}</p>
    </div>
  );
}

// ─── main page ───────────────────────────────────────────────────────────────
const C25AnalysisPageEn: React.FC = () => {
  const navigate = useNavigate();

  useEffect(() => {
    trackPageView(`/analyse/${SLUG}`, "C25 analysis");
    fetch(`${HOST}/stats/visit/c25_analysis/`).catch(() => {});
  }, []);

  return (
    <PageTemplate>
      <title>Why C25 has stood still for 5 years | Zirium</title>
      <meta
        name="description"
        content="C25 has lost 2% over 5 years, while the S&P 500 is up 79% and European peers around 41%. We examine the sector shift, the biggest winners and losers, and what explains Denmark's underperformance."
      />
      <meta property="og:title" content="Why C25 has stood still for 5 years" />
      <meta property="og:description" content="C25 -2% while peers gained 40-79%. Sector shifts and single-stock collapses explain the Danish lag." />
      <meta property="og:type" content="article" />
      <meta property="og:url" content={`https://www.zirium.dk/analyse/${SLUG}`} />
      <meta property="og:image" content="https://www.zirium.dk/og-images/c25-2026-05-28-en.png" />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:type" content="image/png" />
      <meta property="og:site_name" content="Zirium" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Why C25 has stood still for 5 years" />
      <meta name="twitter:description" content="C25 -2% while peers gained 40-79%. Sector shifts and single-stock collapses explain the Danish lag." />
      <meta name="twitter:image" content="https://www.zirium.dk/og-images/c25-2026-05-28-en.png" />
      <script type="application/ld+json">{JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "Why C25 has stood still for 5 years",
        "description": "C25 has lost 2% over 5 years, while the S&P 500 is up 79% and European peers around 41%.",
        "author": { "@type": "Person", "name": "Araz Bayat Makoo" },
        "publisher": { "@type": "Organization", "name": "Zirium", "url": "https://www.zirium.dk" },
        "datePublished": "2026-05-28",
        "mainEntityOfPage": `https://www.zirium.dk/analyse/${SLUG}`,
        "inLanguage": "en",
      })}</script>

      <article className="w-full max-w-[900px] mx-auto px-5 sm:px-8 pb-10 sm:pb-16">
        <button
          className="text-blue-600 hover:text-blue-700 bg-transparent border-none text-base inline-flex items-center gap-1.5 focus:ring-2 focus:ring-blue-300 rounded-sm min-h-[44px] min-w-[44px]"
          onClick={() => {
            if (window.history.length > 1 && window.history.state?.idx > 0) {
              navigate(-1);
            } else {
              navigate("/analyse");
            }
          }}
        >
          <span aria-hidden="true">←</span>
          Back
        </button>

        {/* Header */}
        <header className="mb-10 mt-4">
          <p className="text-base text-gray-600 dark:text-gray-300 mb-4">
            Analysis by Araz Bayat Makoo (Zirium), May 28, 2026
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-gray-900 dark:text-white mb-3 leading-tight">
            Why C25 has stood still for 5 years
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 leading-relaxed">
            OMX Copenhagen 25 (C25)
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            On a price-index basis in local currency, C25 has lost 1.6% over
            the past 5 years (May 28, 2021 to May 27, 2026), while the S&P
            500 is up 78.9%, STOXX Europe 600 is up 40.6% and OMX Stockholm
            30 is up 40.8%. Even Denmark's closest Nordic neighbour has
            delivered roughly 42 percentage points more than the Danish
            market.
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            Danish equities have long been viewed as a European quality
            market: Dominance in healthcare, globally exporting brands,
            high corporate governance and stable dividends. Over the past
            5 years, that status has been challenged by large sector shifts
            and single-stock collapses that have pulled the aggregate
            return below zero.
          </p>
          <p className="text-gray-600 dark:text-gray-300 mt-3 leading-relaxed">
            The official Nasdaq Index factsheets show how dramatically the
            index has shifted. At the end of 2021, healthcare made up 41.6%
            of C25; according to the latest factsheet (March 31, 2026) it
            is down to 33.2%. Financials have gone the other way, from 6.8%
            to 16.9%. Danske Bank alone has grown from 3.4% of the index to
            10.8% over the same period. Structurally, C25 has no mega-cap
            tech exposure comparable to the US hyperscalers or platform
            companies.
          </p>
        </header>

        {/* KPIs */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-12">
          <KPI value="+78.9%" label="S&P 500 (5y)" highlight tone="green" />
          <KPI value="+40.8%" label="OMX Stockholm 30 (5y)" />
          <KPI value="+40.6%" label="STOXX 600 (5y)" />
          <KPI value="-1.6%" label="OMX C25 (5y)" highlight tone="red" />
        </div>

        {/* Section 1 */}
        <section className="mb-12">
          <SectionHeader n={1} title="How sluggish is it really?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Let's look at the numbers. C25 has lost roughly 2% over the past
            five years, while the Nasdaq Composite is up 94% and the S&P 500
            is up 79%. Closer to home, the gap has been just as wide: Both
            STOXX Europe 600 and OMX Stockholm 30 have delivered around 41%.
            Even the closest Nordic market has delivered around 42 percentage
            points more than the Danish one.
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Chart: comparison of C25, S&P 500, Nasdaq Composite, STOXX 600 and OMX Stockholm 30 over 5 years">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Comparison of 5 indices (May 2021 = 100)</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Month-end, price index (excluding dividends)</p>
            <ResponsiveContainer width="100%" height={320}>
              <LineChart data={COMPARISON_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis
                  dataKey="date"
                  tick={{ fontSize: 11, fill: "#6b7280" }}
                  tickFormatter={formatDate}
                  interval={11}
                />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} domain={[70, 200]} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => Number(v).toFixed(1)}
                  labelFormatter={(label) => formatDate(String(label))}
                />
                <Legend wrapperStyle={{ fontSize: 12 }} />
                <ReferenceLine y={100} stroke="#9ca3af" strokeDasharray="3 3" />
                <Line type="monotone" dataKey="nasdaq" name="Nasdaq Composite" stroke="#f59e0b" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="sp500" name="S&P 500" stroke="#10b981" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="omx" name="OMX Stockholm 30" stroke="#3b82f6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="stoxx" name="STOXX Europe 600" stroke="#8b5cf6" strokeWidth={2} dot={false} />
                <Line type="monotone" dataKey="c25" name="OMX C25" stroke="#ef4444" strokeWidth={3} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>

          <p className="text-xs text-gray-500 dark:text-gray-400 italic leading-relaxed">
            Note: The comparison uses price indices without reinvested
            dividends to ensure comparability across the five indices.
            Returns are measured in local currency (USD, EUR, SEK, DKK) and
            are not currency-adjusted. Since the DKK is pegged to the EUR,
            C25 vs. STOXX 600 is effectively currency-neutral; for the S&P
            500 and OMX Stockholm 30 a currency adjustment could move the
            numbers by a few percentage points but would not close the large
            gap to C25.
          </p>
        </section>

        {/* Section 2 */}
        <section className="mb-12">
          <SectionHeader n={2} title="The sector shift" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            If you only look at the index level (-1.6% over 5 years), it
            might seem as if nothing has happened in C25. But that's wrong.
            Beneath the surface, the composition of the index has shifted
            markedly. The clearest story isn't about individual stocks, but
            about which sectors have grown in weight and which have shrunk.
          </p>

          <div className="bg-white dark:bg-[#19191f] rounded-2xl border border-gray-100 dark:border-gray-800 p-3 sm:p-5 mb-4" role="img" aria-label="Chart: C25 sector weights over time (Sept 2020, Dec 2021, March 2026)">
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">C25 sector weights over time</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">Percent of index. Source: Nasdaq Index factsheets.</p>
            <ResponsiveContainer width="100%" height={340}>
              <BarChart data={SECTOR_TIMELINE_DATA} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" strokeOpacity={0.3} />
                <XAxis dataKey="sector" tick={{ fontSize: 11, fill: "#6b7280" }} />
                <YAxis tick={{ fontSize: 11, fill: "#6b7280" }} tickFormatter={(v) => `${v}%`} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => `${Number(v).toFixed(2)}%`}
                />
                <Legend
                  wrapperStyle={{ fontSize: 12 }}
                  content={() => (
                    <ul className="flex flex-wrap justify-center gap-x-4 gap-y-1 pt-2 text-xs text-gray-700 dark:text-gray-300">
                      {[
                        { label: "Sept 2020", color: "#64748b" },
                        { label: "Dec 2021", color: "#0284c7" },
                        { label: "March 2026", color: "#2563eb" },
                      ].map((item) => (
                        <li key={item.label} className="flex items-center gap-1.5">
                          <span className="inline-block w-3 h-3 rounded-sm" style={{ backgroundColor: item.color }} />
                          {item.label}
                        </li>
                      ))}
                    </ul>
                  )}
                />
                <Bar dataKey="y2020" name="Sept 2020" fill="#64748b" radius={[3, 3, 0, 0]} />
                <Bar dataKey="y2021" name="Dec 2021" fill="#0284c7" radius={[3, 3, 0, 0]} />
                <Bar dataKey="y2026" name="March 2026" fill="#2563eb" radius={[3, 3, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            The most striking move is in financials. From 5% of C25 in 2020
            and 7% at the end of 2021, Financials now make up 17% of the
            index, a tripling in five years. This is purely market-driven:
            The banks got a historic boost when the Danish central bank
            (Nationalbanken) and the ECB hiked rates out of negative
            territory in 2022, and their share prices surged. Danske Bank
            also benefited from a re-rating after the money laundering
            scandal was settled with a DKK 15.3 billion agreement with US
            and Danish authorities in December 2022, which removed a major
            legal overhang that had weighed on the stock since 2018. The
            bank has grown from 3% of the index in 2021 to 11% today.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            Healthcare has gone the other way, shrinking from 47% to 33%.
            It's a broad-based decline driven by GN Store Nord (-81%), Ambu
            (-71%), Coloplast (-52%) and Genmab (-29%), while Novo Nordisk,
            despite the media attention, has delivered just +32% over 5
            years (the stock peaked at DKK 1,028 in June 2024 and has since
            fallen 72%). Note that C25 has a 20% single-stock cap which was
            binding while Novo was at its peak. Novo is now down to 12% of
            the index, so the cap is no longer binding.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
            Tech exposure was never large, but is now 0%. Netcompany, the
            last Danish tech name in C25, dropped out of the index during
            the period. By comparison, tech makes up around 32% of the S&P
            500, a structural difference that alone explains a large part
            of the US lead.
          </p>

          <p className="text-xs text-gray-500 dark:text-gray-400 italic leading-relaxed mt-4">
            Sources: Nasdaq Index factsheets dated September 30, 2020,
            December 30, 2021 and March 31, 2026 (sector weights and
            single-stock index weights). Nasdaq reclassified its sector
            system between 2020 and 2021; the figures above are
            consolidated into comparable categories. Stock returns: Yahoo
            Finance via yfinance, dividend-adjusted prices, May 26, 2021 to
            May 27, 2026. S&P 500 tech weight: S&P Dow Jones Indices, May
            2026.
          </p>
        </section>

        {/* Section 3: Losers */}
        <section className="mb-12">
          <SectionHeader n={3} title="The individual stock stories at the bottom" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-6">
            Behind the flat index number lie some of the largest single-stock
            declines seen in a major Danish index in recent times. Here are
            the C25 stocks that have lost the most. Not as "contributions"
            to the index, but as standalone investment stories.
          </p>

          <StockBlock name="Ørsted" returnLabel="-82%">
            The largest decline in C25. The stock hit its all-time high of
            DKK 1,355 on January 7, 2021, and trades today around DKK 165,
            roughly 88% below the peak. The loss reflects a combination of
            rising rates (which hit all long-duration green stocks hard),
            soaring component prices, delays in US offshore projects, and a
            large DKK 28.4 billion impairment in October 2023 when Ørsted
            had to walk away from Ocean Wind 1 and 2 off New Jersey. The
            pressure continued in 2025, when Ørsted had to launch a rights
            issue of around DKK 60 billion because US regulatory uncertainty
            made it impossible to finance Sunrise Wind through a planned
            partial divestment. That triggered significant share dilution.
            This was not a company in operational crisis. It was the entire
            offshore wind business model that suddenly looked unattractive.
          </StockBlock>

          <StockBlock name="GN Store Nord" returnLabel="-81%">
            Just as bad as Ørsted, but less well known to the public. Three
            simultaneous problems hit the company: A post-COVID collapse in
            the Jabra headset business (consumers and companies stockpiled
            headsets during the pandemic and stopped re-purchasing
            afterwards),
            pressure on the ReSound hearing-aid franchise in the US from
            over-the-counter competitors sold via Amazon and pharmacies at
            a fraction of the price, and an expensive SteelSeries
            acquisition for DKK 8 billion in January 2022 that has not
            delivered the expected gaming synergies. GN has since announced
            the sale of the Hearing division to Italian Amplifon to
            transform itself into a pure-play Audio + Gaming company.
          </StockBlock>

          <StockBlock name="Ambu" returnLabel="-71%">
            The same post-COVID pattern as GN. Ambu's single-use endoscopes
            were hot during the pandemic when reusable equipment was seen
            as an infection risk. Structural growth has never returned to
            pre-COVID levels. Britt Meelby Jensen took over as CEO in May
            2022 and has executed a comprehensive focus and cost-cutting
            programme, which has gradually improved margins through 2024
            and 2025. The stock has yet to reclaim its pandemic levels.
          </StockBlock>

          <StockBlock name="Coloplast" returnLabel="-52%">
            Three simultaneous headwinds: Chinese volume pressure on
            continence products, a high purchase price (USD 1.3 billion ≈
            DKK 8.9 billion) for Kerecis in August 2023 that has not
            delivered as expected, and a broad re-rating of defensive
            healthcare stocks in a higher-rate environment.
          </StockBlock>

          <StockBlock name="Royal Unibrew" returnLabel="-39%">
            Margin pressure from raw material prices (notably aluminium and
            malt), a violent spike in input costs in 2022, and growth
            stagnation in developed markets.
          </StockBlock>

          <StockBlock name="Genmab" returnLabel="-29%">
            Patent fears around Darzalex (the US patent expires in 2029 and
            the royalty stream is phased out gradually through the early
            2030s), plus disappointing new product launches have put the
            stock under pressure despite steadily growing royalty income.
            Genmab has tried to broaden the pipeline with its largest M&A
            deal to date, the ProfoundBio acquisition for USD 1.8 billion
            in May 2024 (an ADC platform targeting ovarian cancer among
            others), but the full value uplift remains several years out.
          </StockBlock>

          <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed mt-4">
            Additional large losses in the period: Bavarian Nordic (-30%),
            Rockwool B (-26%), Vestas (-24%), Demant (-23%), Pandora (-16%),
            Novonesis B (-11%), Carlsberg B (-7%).
          </p>
        </section>

        {/* Section 4: Winners */}
        <section className="mb-12">
          <SectionHeader n={4} title="The individual stock stories at the top" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-6">
            Even though the index is flat, a handful of stocks have
            delivered massive returns. In contrast to the losses, the big
            gains are highly concentrated: Banks and infrastructure
            suppliers dominate the top.
          </p>

          <StockBlock name="NKT" returnLabel="+320%">
            By far the biggest winner in C25 over 5 years, larger than any
            bank. NKT makes high-voltage power cables, including subsea
            cables for offshore wind projects. The global build-out of the
            electricity grid and the electrification of industry and
            transport have generated an order book of historic size. This
            is the classic "picks and shovels" story: While developers like
            Ørsted have suffered, suppliers like NKT have benefited from
            the same green transition.
          </StockBlock>

          <StockBlock name="Danske Bank" returnLabel="+299%">
            The second-largest gain in C25. Three simultaneous drivers:
            Net-interest margins exploded after the ECB hiked its deposit
            rate from -0.5% in 2022 to 4.0% in September 2023 (the MRO
            rate up to 4.5%), and the Danish central bank followed up to
            3.6%. Banks thus enjoyed a wide spread between deposit and
            lending rates; historically aggressive share buybacks; and a
            re-rating as the money laundering scandal was gradually
            forgotten by the market. The stock traded at 0.5x P/B in 2020,
            now around 1.6x.
          </StockBlock>

          <StockBlock name="Jyske Bank" returnLabel="+214%">
            The same rate theme as Danske Bank, combined with even more
            aggressive share buybacks relative to market value.
          </StockBlock>

          <StockBlock name="ISS" returnLabel="+125%">
            A comeback story after a brutal 2020-2021 in which the facility
            services company was hit hard by lockdowns and remote work. The
            stock is now around 2-3x its pandemic low, driven by
            normalisation, cost cuts and contract wins.
          </StockBlock>

          <StockBlock name="FLSmidth" returnLabel="+117%">
            The cement and mining-equipment supplier has benefited from the
            global infrastructure and commodities theme. The company has
            divested its cement business and is now focused 100% on mining,
            a transformation the market has rewarded.
          </StockBlock>

          <StockBlock name="A.P. Møller-Mærsk" returnLabel="+70% / +75%">
            Mærsk B ended up +70%, Mærsk A +75%. A wild ride: The stock
            doubled in 2021-2022 during the COVID shipping boom, collapsed
            in 2023 when freight rates normalised, and has since climbed
            back, driven by the Red Sea diversion (Houthi attacks) which
            has kept rates elevated.
          </StockBlock>

          <StockBlock name="Zealand Pharma" returnLabel="+69%">
            The strongest healthcare winner in C25 over the period. Driven
            by clinical progress in the company's pipeline (GLP-1 and
            glucagon-based treatments), notably survodutide, developed
            together with Boehringer Ingelheim, which has validated the
            business.
          </StockBlock>

          <StockBlock name="Novo Nordisk" returnLabel="+32%">
            Here is the surprise. Novo has dominated Danish media headlines
            for years as "Europe's most valuable company", yet over this
            specific 5-year period the stock is only up 32%. The stock
            rose sharply from 2021 to mid-2024 (driven by Wegovy and
            Ozempic), followed by a hard correction when CagriSema data
            disappointed in December 2024, when competition from Eli
            Lilly's Zepbound became clear, and as concerns over US drug
            pricing took over.
          </StockBlock>

          <StockBlock name="Tryg" returnLabel="+30%">
            Insurance isn't banking, but it has the same rate tailwind:
            Higher rates on reserves deliver better investment results.
            Stable dividends and a defensive profile have also helped in
            an uncertain market.
          </StockBlock>

          <StockBlock name="DSV" returnLabel="+9%">
            The largest single weight in C25 today (15.5% per the Nasdaq
            factsheet from March 31, 2026), yet over 5 years it has only
            delivered +9%. Over a period in which the S&P 500 is up 79%,
            this is effectively an underperformance story hiding at the
            top of the table.
          </StockBlock>

        </section>

        {/* Section 5: Structural reasons */}
        <section className="mb-12">
          <SectionHeader n={5} title="Why is C25 structurally trapped?" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            Even if we take the 5-year underperformance with a grain of
            salt (timing is never perfect), there are structural reasons
            why C25 has a hard time keeping up with global indices.
          </p>
          <ol className="space-y-3 text-gray-600 dark:text-gray-300 leading-relaxed list-decimal pl-6 mb-4">
            <li>
              <strong>The historical quality premium is being unwound.</strong>{" "}
              Danish equities have long traded at a premium to both
              European and Nordic peers. The explanation was stable
              dividends, high corporate governance and a world-class
              healthcare sector. Over the past 5 years, that status has
              been challenged by rate-hike pressure on defensive
              "expensive" stocks and by concrete disappointments in
              healthcare. Even if earnings had been unchanged, lower
              multiples alone would have cost C25 significantly.
            </li>
            <li>
              <strong>No tech exposure.</strong> While the S&P 500 has about
              32% in Information Technology, driven by mega-cap tech-related
              companies such as Apple, Microsoft, Nvidia, Alphabet, Amazon
              and Meta, C25 now has 0% in tech. Netcompany was the last
              Danish tech name and dropped out of the index during the
              period. There simply are no Danish mega-cap tech companies
              listed on Nasdaq Copenhagen.
            </li>
            <li>
              <strong>Healthcare overweight creates concentration risk.</strong>{" "}
              Healthcare makes up around 33% of C25 today, and was 47%
              five years ago. When that sector is pressured (as in
              2023-2024), the entire index is pressured. It is built into
              the index, not a temporary condition.
            </li>
            <li>
              <strong>Exposure to the "wrong" part of the green
              transition.</strong> Ørsted (offshore developer) lost 82%,
              Vestas (turbine maker) lost 24%. Meanwhile, NKT (cable
              infrastructure) gained 320%. Unfortunately, C25 has far
              more capital in the losing segments than in the winning
              segments, and even a strong NKT rally cannot compensate
              for the weight in Ørsted.
            </li>
            <li>
              <strong>Concentration in a few sectors.</strong> Healthcare,
              Industrials and Financials make up 78% of the index. Three
              sectors decide the direction of the whole market.
            </li>
          </ol>
        </section>

        {/* Section 6: Conclusion */}
        <section className="mb-12">
          <SectionHeader n={6} title="Conclusion" />
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            C25 has ended around 2% lower over 5 years, while peer indices
            have delivered 40-79%. It is not the fault of any single
            company, but the combination of a handful of large single-stock
            collapses (Ørsted, GN, Ambu, Coloplast), a healthcare sector
            broadly hit by re-rating, and a sector composition that lacks
            the growth segments (tech) that have driven other markets.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            The dramatic shift in the index's weights tells the story:
            Financials have tripled from 5% to 17%, healthcare has shrunk
            from 47% to 33%, and tech exposure has vanished entirely. This
            isn't the result of design, but of banks delivering massive
            returns while other parts of the index have disappointed.
          </p>
          <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-3">
            If you primarily have exposure to C25 (via passive index
            investing or individual Danish stocks), it's worth asking:
            Where in your portfolio do you offset these structural biases?
            If nowhere, it may make sense to complement it with a global
            equity fund. There's no rule that says the home market must
            be the core of your portfolio, especially when it makes up
            only around 0.5% of the global equity market.
          </p>
        </section>

        {/* Feedback widget */}
        <FeedbackWidget pageType="analysis" pageId={SLUG} />

        {/* Related */}
        <RelatedAnalyses currentSlug={SLUG} />

        {/* Disclaimer */}
        <footer className="border-t border-gray-100 dark:border-gray-800 pt-6">
          <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed text-center">
            <strong>Sources:</strong> Yahoo Finance via yfinance (stock and
            index returns), official Nasdaq Index factsheets (sector
            weights).{" "}
            <strong>Disclaimer:</strong>{" "}
            This analysis is for informational purposes only and does not
            constitute investment advice. Past performance is no guarantee
            of future results. Always do your own research and consult a
            professional advisor before trading.
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-400 text-center mt-3">
            Copyright Zirium  |  May 28, 2026
          </p>
        </footer>
      </article>
    </PageTemplate>
  );
};

export default C25AnalysisPageEn;
