# Generated by Django 4.1.3 on 2024-07-28 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorts', '0022_companymap_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('device', models.CharField(max_length=6)),
                ('notification_active', models.BooleanField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('invalid', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=6)),
                ('notifications_sent', models.IntegerField(default=0)),
                ('stocks', models.ManyToManyField(blank=True, related_name='app_users', to='shorts.stock')),
            ],
        ),
    ]
