# Generated by Django 4.1.3 on 2024-08-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_webuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='client_ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
    ]
