# Generated by Django 4.1.3 on 2024-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_webuser_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='consent_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='old_consent_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
