# Generated by Django 4.1.3 on 2024-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appuser_consent_accepted_appuser_consent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
