# Generated by Django 4.1.3 on 2026-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_webuser_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
