# Generated by Django 4.1.3 on 2023-10-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('requested_url', models.TextField()),
            ],
        ),
    ]
