# Generated by Django 4.1.3 on 2024-06-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_logging', '0002_requestlog_referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('first', models.DateTimeField()),
                ('previous', models.DateTimeField(null=True)),
                ('last', models.DateTimeField()),
                ('visits', models.PositiveBigIntegerField()),
                ('visits_today', models.PositiveBigIntegerField()),
                ('watch', models.TextField(blank=True)),
                ('pick', models.TextField(blank=True)),
                ('web', models.DateTimeField(null=True)),
                ('visits_web', models.PositiveBigIntegerField(default=0)),
                ('iphone', models.DateTimeField(null=True)),
                ('visits_iphone', models.PositiveBigIntegerField(default=0)),
                ('ipad', models.DateTimeField(null=True)),
                ('visits_ipad', models.PositiveBigIntegerField(default=0)),
                ('iwatch', models.DateTimeField(null=True)),
                ('visits_iwatch', models.PositiveBigIntegerField(default=0)),
                ('version', models.CharField(max_length=5, null=True)),
                ('referer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.CharField(default='X', max_length=1, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='requestlog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
