# Generated by Django 5.2.7 on 2026-04-26 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_logging', '0003_visitor_visitorlock_requestlog_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
