# Generated by Django 5.2.7 on 2026-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_logging', '0004_alter_requestlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
