# Generated by Django 5.2.7 on 2026-05-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_logging', '0006_alter_requestlog_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('bug', 'Bug rapport'), ('feedback', 'Feedback'), ('idea', 'Idé'), ('other', 'Andet')], max_length=20)),
                ('message', models.TextField()),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
