# Generated by Django 5.2.7 on 2026-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_logging', '0007_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sentiment', models.CharField(choices=[('positive', '👍 Positive'), ('negative', '👎 Negative')], db_index=True, max_length=10)),
                ('page_type', models.CharField(db_index=True, max_length=50)),
                ('page_id', models.CharField(db_index=True, max_length=200)),
                ('comment', models.TextField(blank=True, default='')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
