# Generated by Django 5.2.7 on 2026-05-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_logging', '0008_pagefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug rapport'), ('feedback', 'Feedback'), ('idea', 'Idé'), ('analysis', 'Analyse'), ('other', 'Andet')], max_length=20),
        ),
    ]
