# Generated by Django 5.2.7 on 2026-05-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_logging', '0009_alter_contactsubmission_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='VisitorLock',
        ),
    ]
