# Generated by Django 4.1.3 on 2023-10-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortwatchuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shortwatchuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
