# Generated by Django 5.2.7 on 2026-05-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderIssuer',
            fields=[
                ('cvr', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lei', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsiderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_id', models.CharField(max_length=100, unique=True)),
                ('published_date', models.DateField()),
                ('person_name', models.CharField(max_length=255)),
                ('person_role', models.CharField(blank=True, default='', max_length=255)),
                ('closely_associated_to', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=100)),
                ('instrument_type', models.CharField(blank=True, default='', max_length=100)),
                ('instrument_name', models.CharField(blank=True, default='', max_length=255)),
                ('isin', models.CharField(blank=True, default='', max_length=20)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('extraction_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='insider_transactions.insiderissuer')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
