# Generated by Django 5.2.7 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidertransaction',
            name='announcement_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
