# Generated by Django 5.2.7 on 2026-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider_transactions', '0003_processedannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='insidertransaction',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
