# Generated by Django 5.2.7 on 2026-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider_transactions', '0004_insidertransaction_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedannouncement',
            name='skip_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
