# Generated by Django 5.2.7 on 2026-05-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider_transactions', '0005_add_skip_reason_to_processed_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='insiderissuer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insiderissuer',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
