# Generated by Django 5.2.7 on 2026-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider_transactions', '0006_add_symbol_active_to_insider_issuer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='insidertransaction',
            index=models.Index(fields=['issuer', '-published_date'], name='insider_tra_issuer__518506_idx'),
        ),
    ]
