# Generated by Django 4.1.3 on 2025-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='user_id',
            field=models.UUIDField(default='c45d9670-3461-4607-868b-08ded20b8a2d'),
            preserve_default=False,
        ),
    ]
