# Generated by Django 4.1.3 on 2025-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_measurement_light_level_measurement_noise_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='light_level',
            field=models.IntegerField(),
        ),
    ]
