# Generated by Django 4.1.3 on 2025-03-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_alter_measurement_light_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='light_level',
            new_name='lux',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='noise_level',
        ),
        migrations.AddField(
            model_name='measurement',
            name='als',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='aqi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='db',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='eco2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='tvoc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='white',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
