# Generated by Django 4.1.3 on 2023-10-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField()),
            ],
        ),
    ]
