# Generated by Django 4.1.3 on 2023-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_alter_runstatus_options_alter_runstatus_executed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameSymbolMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
            ],
        ),
    ]
