# Generated by Django 4.1.3 on 2023-10-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0004_namesymbolmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='namesymbolmap',
            name='code',
            field=models.CharField(default='DK', max_length=20),
            preserve_default=False,
        ),
    ]
