# Generated by Django 4.1.3 on 2023-10-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0005_namesymbolmap_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameSymbolMap',
            new_name='SymbolMap',
        ),
    ]
