# Generated by Django 4.1.3 on 2023-10-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0006_rename_namesymbolmap_symbolmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortedstock',
            old_name='date',
            new_name='timestamp',
        ),
    ]
