# Generated by Django 4.1.3 on 2023-11-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0007_rename_date_shortedstock_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_id', models.CharField(max_length=20)),
                ('stock_code', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
