# Generated by Django 4.1.3 on 2023-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0008_shortseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortedStockChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
