# Generated by Django 4.1.3 on 2023-11-14 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0009_shortedstockchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortedstockchart',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 5, 6, 23, 418605, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
