# Generated by Django 4.1.3 on 2023-12-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0010_shortedstockchart_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SymbolMap',
            new_name='Stock',
        ),
    ]
