# Generated by Django 4.1.3 on 2023-12-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0012_remove_stock_id_alter_stock_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortedStock',
            new_name='ShortPosition',
        ),
    ]
