# Generated by Django 4.1.3 on 2023-12-02 12:51

from django.db import migrations


def populate_short_position_chart_code(apps, schema_editor):
    ShortPositionChart = apps.get_model('shorts', 'ShortPositionChart')
    Stock = apps.get_model('shorts', 'Stock')

    for short_position_chart in ShortPositionChart.objects.all():
        try:
            short_position_chart.stock = Stock.objects.get(code=short_position_chart.code)
            short_position_chart.save()
        except Stock.DoesNotExist:
            print('Error')
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0019_shortpositionchart_stock'),
    ]

    operations = [
        migrations.RunPython(populate_short_position_chart_code),
    ]
