# Generated by Django 4.1.3 on 2023-12-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0020_auto_20231202_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortposition',
            name='code',
        ),
        migrations.RemoveField(
            model_name='shortposition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shortpositionchart',
            name='code',
        ),
        migrations.RemoveField(
            model_name='shortpositionchart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shortseller',
            name='stock_code',
        ),
        migrations.RemoveField(
            model_name='shortseller',
            name='stock_name',
        ),
    ]
