# Generated by Django 4.1.3 on 2024-07-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0021_remove_shortposition_code_remove_shortposition_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_company_name', models.CharField(max_length=150)),
                ('issuer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shorts.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_company_name', models.CharField(max_length=150)),
                ('announcement_number', models.CharField(max_length=20)),
                ('cvr_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('headline', models.CharField(max_length=600)),
                ('headline_danish', models.CharField(max_length=600)),
                ('issuer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('shortselling_type', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('notification_datetime_to_company', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField()),
                ('registration_date', models.DateTimeField()),
                ('registration_datetime', models.DateTimeField()),
                ('is_historic', models.BooleanField(blank=True, null=True)),
                ('shortselling_country', models.CharField(blank=True, max_length=70, null=True)),
                ('shortselling_country_danish', models.CharField(blank=True, max_length=70, null=True)),
                ('dfsa_id', models.CharField(max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shorts.stock')),
            ],
        ),
    ]
