# Generated by Django 4.1.3 on 2024-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0021_remove_shortposition_code_remove_shortposition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpositionchart',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shortpositionchart',
            name='volume',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
