# Generated by Django 4.1.3 on 2024-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0022_companymap_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortposition',
            name='prev_value',
            field=models.FloatField(default=0),
        ),
    ]
