# Generated by Django 4.1.3 on 2024-08-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0023_shortposition_prev_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortseller',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shortseller',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='shortseller',
            name='value',
        ),
        migrations.AddField(
            model_name='announcement',
            name='short_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shorts.shortseller'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortseller',
            name='business_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LargeShortSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_id', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shorts.stock')),
            ],
        ),
    ]
