# Generated by Django 4.1.3 on 2024-08-30 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0024_remove_shortseller_date_remove_shortseller_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortseller',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
