# Generated by Django 4.1.3 on 2024-08-30 07:41

from django.db import migrations, models
import django.db.models.deletion
import shorts.models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0025_alter_shortseller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='largeshortselling',
            name='short_seller',
            field=models.ForeignKey(blank=True, default=shorts.models.get_default_short_seller, null=True, on_delete=django.db.models.deletion.PROTECT, to='shorts.shortseller'),
        ),
    ]
