# Generated by Django 4.1.3 on 2024-08-30 07:53

from django.db import migrations, models
import django.db.models.deletion
import shorts.models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0026_largeshortselling_short_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largeshortselling',
            name='short_seller',
            field=models.ForeignKey(default=shorts.models.get_default_short_seller, on_delete=django.db.models.deletion.PROTECT, to='shorts.shortseller'),
        ),
    ]
