# Generated by Django 5.1 on 2024-08-31 12:52

import django.db.models.deletion
import shorts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0027_alter_largeshortselling_short_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='short_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='shorts.shortseller'),
        ),
        migrations.AlterField(
            model_name='largeshortselling',
            name='short_seller',
            field=models.ForeignKey(default=shorts.models.get_default_short_seller, on_delete=django.db.models.deletion.PROTECT, related_name='large_short_sellings', to='shorts.shortseller'),
        ),
    ]
