# Generated by Django 4.1.3 on 2024-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0028_alter_announcement_short_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='largeshortselling',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortpositionchart',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortpositionchart',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
