# Generated by Django 4.1.3 on 2024-09-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0029_largeshortselling_delete_shortpositionchart_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='largeshortselling',
            name='prev_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
