# Generated by Django 4.1.3 on 2024-09-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0030_largeshortselling_prev_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
