# Generated by Django 4.1.3 on 2026-04-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0031_stock_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announced_company_name',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_number',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='cvr_company_name',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='notification_datetime_to_company',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='registration_datetime',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='shortselling_country',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='shortselling_country_danish',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='shortselling_type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='status',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='dfsa_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='headline_danish',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_historic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(default='Shortselling', max_length=30),
        ),
        migrations.AlterField(
            model_name='shortseller',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
