# Generated by Django 5.2.7 on 2026-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0033_stock_shares_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpositionchart',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortpositionchart',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
