# Generated by Django 5.2.7 on 2026-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0034_add_high_low_to_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='float_shares',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
