# Generated by Django 5.2.7 on 2026-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0035_add_float_shares_to_stock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shortposition',
            index=models.Index(fields=['stock', '-timestamp'], name='shorts_shor_stock_i_f7de41_idx'),
        ),
    ]
