# Generated by Django 5.2.7 on 2026-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0036_shortposition_shorts_shor_stock_i_f7de41_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['stock', '-published_date'], name='shorts_anno_stock_i_7fdba5_idx'),
        ),
        migrations.AddIndex(
            model_name='largeshortselling',
            index=models.Index(fields=['stock', '-date'], name='shorts_larg_stock_i_29da93_idx'),
        ),
        migrations.AddIndex(
            model_name='shortpositionchart',
            index=models.Index(fields=['stock', '-date'], name='shorts_shor_stock_i_438f5e_idx'),
        ),
    ]
