# Generated by Django 5.2.7 on 2026-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0037_announcement_shorts_anno_stock_i_7fdba5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='show_price_data',
            field=models.BooleanField(default=True),
        ),
    ]
